export interface LibraryExercise {
  id: string;
  name: string;
  muscleGroup: string;
  category: string;
  equipment: string;
}

export interface ExerciseCategory {
  id: string;
  name: string;
  muscleGroup: string;
  exercises: LibraryExercise[];
}

export interface MuscleGroup {
  id: string;
  name: string;
  categories: ExerciseCategory[];
}

const exerciseLibrary: MuscleGroup[] = [
  {
    id: "chest",
    name: "CHEST",
    categories: [
      {
        id: "chest-upper",
        name: "Upper Chest",
        muscleGroup: "CHEST",
        exercises: [
          { id: "incline-barbell-press", name: "Incline Bench Press (Barbell)", muscleGroup: "CHEST", category: "Upper Chest", equipment: "Barbell" },
          { id: "incline-dumbbell-press", name: "Incline Dumbbell Press", muscleGroup: "CHEST", category: "Upper Chest", equipment: "Dumbbell" },
          { id: "incline-dumbbell-fly", name: "Incline Dumbbell Fly", muscleGroup: "CHEST", category: "Upper Chest", equipment: "Dumbbell" },
          { id: "reverse-grip-bench", name: "Reverse-Grip Bench Press", muscleGroup: "CHEST", category: "Upper Chest", equipment: "Barbell" },
          { id: "incline-machine-press", name: "Incline Machine Chest Press", muscleGroup: "CHEST", category: "Upper Chest", equipment: "Machine" },
          { id: "high-to-low-cable-fly", name: "High-to-Low Cable Fly", muscleGroup: "CHEST", category: "Upper Chest", equipment: "Cable" },
          { id: "decline-pushup", name: "Decline Push-up", muscleGroup: "CHEST", category: "Upper Chest", equipment: "Bodyweight" },
          { id: "pike-pushup", name: "Pike Push-up", muscleGroup: "CHEST", category: "Upper Chest", equipment: "Bodyweight" },
        ],
      },
      {
        id: "chest-middle",
        name: "Middle Chest",
        muscleGroup: "CHEST",
        exercises: [
          { id: "flat-barbell-bench", name: "Flat Barbell Bench Press", muscleGroup: "CHEST", category: "Middle Chest", equipment: "Barbell" },
          { id: "flat-dumbbell-press", name: "Flat Dumbbell Press", muscleGroup: "CHEST", category: "Middle Chest", equipment: "Dumbbell" },
          { id: "flat-dumbbell-fly", name: "Dumbbell Fly (Flat Bench)", muscleGroup: "CHEST", category: "Middle Chest", equipment: "Dumbbell" },
          { id: "machine-chest-press", name: "Machine Chest Press", muscleGroup: "CHEST", category: "Middle Chest", equipment: "Machine" },
          { id: "cable-crossover", name: "Cable Crossover", muscleGroup: "CHEST", category: "Middle Chest", equipment: "Cable" },
          { id: "standard-pushup", name: "Standard Push-up", muscleGroup: "CHEST", category: "Middle Chest", equipment: "Bodyweight" },
          { id: "chest-dips", name: "Chest Dips", muscleGroup: "CHEST", category: "Middle Chest", equipment: "Bodyweight" },
          { id: "wide-pushup", name: "Wide Push-up", muscleGroup: "CHEST", category: "Middle Chest", equipment: "Bodyweight" },
        ],
      },
      {
        id: "chest-lower",
        name: "Lower Chest",
        muscleGroup: "CHEST",
        exercises: [
          { id: "decline-barbell-press", name: "Decline Bench Press (Barbell)", muscleGroup: "CHEST", category: "Lower Chest", equipment: "Barbell" },
          { id: "decline-dumbbell-press", name: "Decline Bench Press (Dumbbell)", muscleGroup: "CHEST", category: "Lower Chest", equipment: "Dumbbell" },
          { id: "decline-dumbbell-fly", name: "Decline Dumbbell Fly", muscleGroup: "CHEST", category: "Lower Chest", equipment: "Dumbbell" },
          { id: "low-to-high-cable-fly", name: "Low-to-High Cable Fly", muscleGroup: "CHEST", category: "Lower Chest", equipment: "Cable" },
          { id: "decline-chest-press-machine", name: "Decline Chest Press Machine", muscleGroup: "CHEST", category: "Lower Chest", equipment: "Machine" },
          { id: "dips-chest", name: "Dips (Chest Version)", muscleGroup: "CHEST", category: "Lower Chest", equipment: "Bodyweight" },
          { id: "incline-pushup", name: "Incline Push-up", muscleGroup: "CHEST", category: "Lower Chest", equipment: "Bodyweight" },
        ],
      },
      {
        id: "chest-inner",
        name: "Inner Chest",
        muscleGroup: "CHEST",
        exercises: [
          { id: "cable-crossover-squeeze", name: "Cable Crossover (Squeeze Focus)", muscleGroup: "CHEST", category: "Inner Chest", equipment: "Cable" },
          { id: "dumbbell-squeeze-press", name: "Dumbbell Squeeze Press", muscleGroup: "CHEST", category: "Inner Chest", equipment: "Dumbbell" },
          { id: "pec-deck", name: "Pec Deck / Butterfly Machine", muscleGroup: "CHEST", category: "Inner Chest", equipment: "Machine" },
          { id: "diamond-pushup", name: "Diamond Push-up", muscleGroup: "CHEST", category: "Inner Chest", equipment: "Bodyweight" },
        ],
      },
    ],
  },
  {
    id: "arms",
    name: "ARMS",
    categories: [
      {
        id: "biceps",
        name: "Biceps",
        muscleGroup: "ARMS",
        exercises: [
          { id: "barbell-curl", name: "Barbell Curl", muscleGroup: "ARMS", category: "Biceps", equipment: "Barbell" },
          { id: "wide-grip-barbell-curl", name: "Wide-Grip Barbell Curl", muscleGroup: "ARMS", category: "Biceps", equipment: "Barbell" },
          { id: "close-grip-barbell-curl", name: "Close-Grip Barbell Curl", muscleGroup: "ARMS", category: "Biceps", equipment: "Barbell" },
          { id: "reverse-barbell-curl", name: "Reverse Barbell Curl", muscleGroup: "ARMS", category: "Biceps", equipment: "Barbell" },
          { id: "drag-curl", name: "Drag Curl", muscleGroup: "ARMS", category: "Biceps", equipment: "Barbell" },
          { id: "dumbbell-curl", name: "Dumbbell Curl", muscleGroup: "ARMS", category: "Biceps", equipment: "Dumbbell" },
          { id: "incline-dumbbell-curl", name: "Incline Dumbbell Curl", muscleGroup: "ARMS", category: "Biceps", equipment: "Dumbbell" },
          { id: "hammer-curl", name: "Hammer Curl", muscleGroup: "ARMS", category: "Biceps", equipment: "Dumbbell" },
          { id: "concentration-curl", name: "Concentration Curl", muscleGroup: "ARMS", category: "Biceps", equipment: "Dumbbell" },
          { id: "zottman-curl", name: "Zottman Curl", muscleGroup: "ARMS", category: "Biceps", equipment: "Dumbbell" },
          { id: "cross-body-hammer-curl", name: "Cross-Body Hammer Curl", muscleGroup: "ARMS", category: "Biceps", equipment: "Dumbbell" },
          { id: "supinating-curl", name: "Supinating Curl", muscleGroup: "ARMS", category: "Biceps", equipment: "Dumbbell" },
          { id: "cable-curl", name: "Cable Curl", muscleGroup: "ARMS", category: "Biceps", equipment: "Cable" },
          { id: "overhead-cable-curl", name: "Overhead Cable Curl", muscleGroup: "ARMS", category: "Biceps", equipment: "Cable" },
          { id: "rope-hammer-curl", name: "Rope Hammer Curl", muscleGroup: "ARMS", category: "Biceps", equipment: "Cable" },
          { id: "reverse-cable-curl", name: "Reverse-Grip Cable Curl", muscleGroup: "ARMS", category: "Biceps", equipment: "Cable" },
          { id: "single-arm-cable-curl", name: "Single-Arm Cable Curl", muscleGroup: "ARMS", category: "Biceps", equipment: "Cable" },
          { id: "chin-ups", name: "Chin-Ups", muscleGroup: "ARMS", category: "Biceps", equipment: "Bodyweight" },
          { id: "preacher-curl-machine", name: "Preacher Curl Machine", muscleGroup: "ARMS", category: "Biceps", equipment: "Machine" },
          { id: "seated-bicep-curl-machine", name: "Seated Bicep Curl Machine", muscleGroup: "ARMS", category: "Biceps", equipment: "Machine" },
        ],
      },
      {
        id: "triceps",
        name: "Triceps",
        muscleGroup: "ARMS",
        exercises: [
          { id: "close-grip-bench-press", name: "Close-Grip Bench Press", muscleGroup: "ARMS", category: "Triceps", equipment: "Barbell" },
          { id: "skull-crushers", name: "Skull Crushers", muscleGroup: "ARMS", category: "Triceps", equipment: "Barbell" },
          { id: "jm-press", name: "JM Press", muscleGroup: "ARMS", category: "Triceps", equipment: "Barbell" },
          { id: "reverse-grip-bench-press", name: "Reverse-Grip Bench Press", muscleGroup: "ARMS", category: "Triceps", equipment: "Barbell" },
          { id: "overhead-dumbbell-extension", name: "Overhead Dumbbell Extension", muscleGroup: "ARMS", category: "Triceps", equipment: "Dumbbell" },
          { id: "dumbbell-kickback", name: "Dumbbell Kickback", muscleGroup: "ARMS", category: "Triceps", equipment: "Dumbbell" },
          { id: "dumbbell-skull-crusher", name: "Dumbbell Skull Crusher", muscleGroup: "ARMS", category: "Triceps", equipment: "Dumbbell" },
          { id: "dumbbell-close-press", name: "Dumbbell Close-Press", muscleGroup: "ARMS", category: "Triceps", equipment: "Dumbbell" },
          { id: "tate-press", name: "Tate Press", muscleGroup: "ARMS", category: "Triceps", equipment: "Dumbbell" },
          { id: "rope-pushdown", name: "Rope Pushdown", muscleGroup: "ARMS", category: "Triceps", equipment: "Cable" },
          { id: "straight-bar-pushdown", name: "Straight Bar Pushdown", muscleGroup: "ARMS", category: "Triceps", equipment: "Cable" },
          { id: "v-bar-pushdown", name: "V-Bar Pushdown", muscleGroup: "ARMS", category: "Triceps", equipment: "Cable" },
          { id: "overhead-rope-extension", name: "Overhead Rope Extension", muscleGroup: "ARMS", category: "Triceps", equipment: "Cable" },
          { id: "reverse-grip-pushdown", name: "Reverse-Grip Pushdown", muscleGroup: "ARMS", category: "Triceps", equipment: "Cable" },
          { id: "single-arm-cable-kickback", name: "Single-Arm Cable Kickback", muscleGroup: "ARMS", category: "Triceps", equipment: "Cable" },
          { id: "triceps-dips", name: "Triceps Dips", muscleGroup: "ARMS", category: "Triceps", equipment: "Bodyweight" },
          { id: "diamond-pushup-triceps", name: "Diamond Push-Up", muscleGroup: "ARMS", category: "Triceps", equipment: "Bodyweight" },
          { id: "close-grip-pushup", name: "Close-Grip Push-Up", muscleGroup: "ARMS", category: "Triceps", equipment: "Bodyweight" },
          { id: "triceps-extension-machine", name: "Triceps Extension Machine", muscleGroup: "ARMS", category: "Triceps", equipment: "Machine" },
        ],
      },
      {
        id: "forearms",
        name: "Forearms",
        muscleGroup: "ARMS",
        exercises: [
          { id: "wrist-curl-barbell", name: "Wrist Curl (Barbell)", muscleGroup: "ARMS", category: "Forearms", equipment: "Barbell" },
          { id: "reverse-wrist-curl-barbell", name: "Reverse Wrist Curl (Barbell)", muscleGroup: "ARMS", category: "Forearms", equipment: "Barbell" },
          { id: "behind-back-wrist-curl", name: "Behind-the-Back Wrist Curl", muscleGroup: "ARMS", category: "Forearms", equipment: "Barbell" },
          { id: "barbell-reverse-curl-forearm", name: "Barbell Reverse Curl", muscleGroup: "ARMS", category: "Forearms", equipment: "Barbell" },
          { id: "dumbbell-wrist-curl", name: "Dumbbell Wrist Curl", muscleGroup: "ARMS", category: "Forearms", equipment: "Dumbbell" },
          { id: "reverse-dumbbell-curl", name: "Reverse Dumbbell Curl", muscleGroup: "ARMS", category: "Forearms", equipment: "Dumbbell" },
          { id: "hammer-curl-forearm", name: "Hammer Curl", muscleGroup: "ARMS", category: "Forearms", equipment: "Dumbbell" },
          { id: "dumbbell-hold", name: "Dumbbell Hold", muscleGroup: "ARMS", category: "Forearms", equipment: "Dumbbell" },
          { id: "cable-wrist-curl", name: "Cable Wrist Curl", muscleGroup: "ARMS", category: "Forearms", equipment: "Cable" },
          { id: "reverse-cable-curl-forearm", name: "Reverse Cable Curl", muscleGroup: "ARMS", category: "Forearms", equipment: "Cable" },
          { id: "towel-grip-pullup", name: "Towel Grip Pull-Up", muscleGroup: "ARMS", category: "Forearms", equipment: "Bodyweight" },
          { id: "farmers-carry", name: "Farmer's Carry", muscleGroup: "ARMS", category: "Forearms", equipment: "Bodyweight" },
          { id: "dead-hang", name: "Dead Hang from Bar", muscleGroup: "ARMS", category: "Forearms", equipment: "Bodyweight" },
          { id: "wrist-roller", name: "Wrist Roller", muscleGroup: "ARMS", category: "Forearms", equipment: "Machine" },
        ],
      },
    ],
  },
  {
    id: "back",
    name: "BACK",
    categories: [
      {
        id: "back-lat",
        name: "Lat (Width)",
        muscleGroup: "BACK",
        exercises: [
          { id: "bent-over-barbell-row", name: "Bent-Over Barbell Row", muscleGroup: "BACK", category: "Lat (Width)", equipment: "Barbell" },
          { id: "yates-row", name: "Yates Row", muscleGroup: "BACK", category: "Lat (Width)", equipment: "Barbell" },
          { id: "one-arm-dumbbell-row", name: "One-Arm Dumbbell Row", muscleGroup: "BACK", category: "Lat (Width)", equipment: "Dumbbell" },
          { id: "dumbbell-pullover", name: "Dumbbell Pullover", muscleGroup: "BACK", category: "Lat (Width)", equipment: "Dumbbell" },
          { id: "dumbbell-row-both-arms", name: "Dumbbell Row (Both Arms)", muscleGroup: "BACK", category: "Lat (Width)", equipment: "Dumbbell" },
          { id: "lat-pulldown-wide", name: "Lat Pulldown (Wide Grip)", muscleGroup: "BACK", category: "Lat (Width)", equipment: "Cable" },
          { id: "close-grip-pulldown", name: "Close-Grip Pulldown", muscleGroup: "BACK", category: "Lat (Width)", equipment: "Cable" },
          { id: "straight-arm-cable-pulldown", name: "Straight-Arm Cable Pulldown", muscleGroup: "BACK", category: "Lat (Width)", equipment: "Cable" },
          { id: "machine-pulldown", name: "Machine Pulldown", muscleGroup: "BACK", category: "Lat (Width)", equipment: "Machine" },
          { id: "single-arm-lat-pulldown", name: "Single-Arm Lat Pulldown", muscleGroup: "BACK", category: "Lat (Width)", equipment: "Cable" },
          { id: "pullups-wide", name: "Pull-Ups (Wide Grip)", muscleGroup: "BACK", category: "Lat (Width)", equipment: "Bodyweight" },
          { id: "chinups-back", name: "Chin-Ups", muscleGroup: "BACK", category: "Lat (Width)", equipment: "Bodyweight" },
          { id: "neutral-grip-pullups", name: "Neutral Grip Pull-Ups", muscleGroup: "BACK", category: "Lat (Width)", equipment: "Bodyweight" },
        ],
      },
      {
        id: "back-middle",
        name: "Middle Back (Thickness)",
        muscleGroup: "BACK",
        exercises: [
          { id: "barbell-row-middle", name: "Barbell Row", muscleGroup: "BACK", category: "Middle Back", equipment: "Barbell" },
          { id: "pendlay-row", name: "Pendlay Row", muscleGroup: "BACK", category: "Middle Back", equipment: "Barbell" },
          { id: "t-bar-row", name: "T-Bar Row", muscleGroup: "BACK", category: "Middle Back", equipment: "Barbell" },
          { id: "landmine-row", name: "Landmine Row", muscleGroup: "BACK", category: "Middle Back", equipment: "Barbell" },
          { id: "dumbbell-row-middle", name: "Dumbbell Row", muscleGroup: "BACK", category: "Middle Back", equipment: "Dumbbell" },
          { id: "seal-row", name: "Seal Row", muscleGroup: "BACK", category: "Middle Back", equipment: "Dumbbell" },
          { id: "seated-cable-row", name: "Seated Cable Row", muscleGroup: "BACK", category: "Middle Back", equipment: "Cable" },
          { id: "machine-row", name: "Machine Row", muscleGroup: "BACK", category: "Middle Back", equipment: "Machine" },
          { id: "rope-row", name: "Rope Row", muscleGroup: "BACK", category: "Middle Back", equipment: "Cable" },
          { id: "inverted-row", name: "Inverted Row", muscleGroup: "BACK", category: "Middle Back", equipment: "Bodyweight" },
          { id: "bodyweight-row", name: "Bodyweight Row (TRX)", muscleGroup: "BACK", category: "Middle Back", equipment: "Bodyweight" },
        ],
      },
      {
        id: "back-upper",
        name: "Upper Back (Traps)",
        muscleGroup: "BACK",
        exercises: [
          { id: "barbell-shrug", name: "Barbell Shrug", muscleGroup: "BACK", category: "Upper Back", equipment: "Barbell" },
          { id: "upright-row-barbell", name: "Upright Row", muscleGroup: "BACK", category: "Upper Back", equipment: "Barbell" },
          { id: "barbell-high-row", name: "Barbell High Row", muscleGroup: "BACK", category: "Upper Back", equipment: "Barbell" },
          { id: "dumbbell-shrug", name: "Dumbbell Shrug", muscleGroup: "BACK", category: "Upper Back", equipment: "Dumbbell" },
          { id: "dumbbell-reverse-fly", name: "Dumbbell Reverse Fly", muscleGroup: "BACK", category: "Upper Back", equipment: "Dumbbell" },
          { id: "dumbbell-upright-row", name: "Dumbbell Upright Row", muscleGroup: "BACK", category: "Upper Back", equipment: "Dumbbell" },
          { id: "incline-reverse-fly", name: "Incline Reverse Fly", muscleGroup: "BACK", category: "Upper Back", equipment: "Dumbbell" },
          { id: "face-pull", name: "Face Pull", muscleGroup: "BACK", category: "Upper Back", equipment: "Cable" },
          { id: "cable-reverse-fly", name: "Cable Reverse Fly", muscleGroup: "BACK", category: "Upper Back", equipment: "Cable" },
          { id: "cable-shrug", name: "Cable Shrug", muscleGroup: "BACK", category: "Upper Back", equipment: "Cable" },
          { id: "rear-delt-machine-fly", name: "Rear Delt Machine Fly", muscleGroup: "BACK", category: "Upper Back", equipment: "Machine" },
          { id: "scapular-pullup", name: "Scapular Pull-Up", muscleGroup: "BACK", category: "Upper Back", equipment: "Bodyweight" },
        ],
      },
      {
        id: "back-lower",
        name: "Lower Back",
        muscleGroup: "BACK",
        exercises: [
          { id: "deadlift", name: "Deadlift", muscleGroup: "BACK", category: "Lower Back", equipment: "Barbell" },
          { id: "rack-pull", name: "Rack Pull", muscleGroup: "BACK", category: "Lower Back", equipment: "Barbell" },
          { id: "good-morning", name: "Good Morning", muscleGroup: "BACK", category: "Lower Back", equipment: "Barbell" },
          { id: "dumbbell-deadlift", name: "Dumbbell Deadlift", muscleGroup: "BACK", category: "Lower Back", equipment: "Dumbbell" },
          { id: "dumbbell-romanian-deadlift", name: "Dumbbell Romanian Deadlift", muscleGroup: "BACK", category: "Lower Back", equipment: "Dumbbell" },
          { id: "back-extension-machine", name: "Back Extension Machine", muscleGroup: "BACK", category: "Lower Back", equipment: "Machine" },
          { id: "cable-pull-through", name: "Cable Pull-Through", muscleGroup: "BACK", category: "Lower Back", equipment: "Cable" },
          { id: "reverse-hyperextension", name: "Reverse Hyperextension", muscleGroup: "BACK", category: "Lower Back", equipment: "Machine" },
          { id: "hyperextension", name: "Hyperextension", muscleGroup: "BACK", category: "Lower Back", equipment: "Bodyweight" },
          { id: "superman-hold", name: "Superman Hold", muscleGroup: "BACK", category: "Lower Back", equipment: "Bodyweight" },
          { id: "bird-dog", name: "Bird Dog", muscleGroup: "BACK", category: "Lower Back", equipment: "Bodyweight" },
        ],
      },
    ],
  },
  {
    id: "shoulders",
    name: "SHOULDERS",
    categories: [
      {
        id: "shoulders-front",
        name: "Front Deltoid",
        muscleGroup: "SHOULDERS",
        exercises: [
          { id: "barbell-overhead-press", name: "Barbell Overhead Press", muscleGroup: "SHOULDERS", category: "Front Deltoid", equipment: "Barbell" },
          { id: "front-press", name: "Front Press", muscleGroup: "SHOULDERS", category: "Front Deltoid", equipment: "Barbell" },
          { id: "landmine-press", name: "Landmine Press", muscleGroup: "SHOULDERS", category: "Front Deltoid", equipment: "Barbell" },
          { id: "dumbbell-shoulder-press", name: "Dumbbell Shoulder Press", muscleGroup: "SHOULDERS", category: "Front Deltoid", equipment: "Dumbbell" },
          { id: "arnold-press", name: "Arnold Press", muscleGroup: "SHOULDERS", category: "Front Deltoid", equipment: "Dumbbell" },
          { id: "front-raise", name: "Front Raise", muscleGroup: "SHOULDERS", category: "Front Deltoid", equipment: "Dumbbell" },
          { id: "neutral-grip-shoulder-press", name: "Neutral Grip Shoulder Press", muscleGroup: "SHOULDERS", category: "Front Deltoid", equipment: "Dumbbell" },
          { id: "incline-front-raise", name: "Incline Front Raise", muscleGroup: "SHOULDERS", category: "Front Deltoid", equipment: "Dumbbell" },
          { id: "cable-front-raise", name: "Cable Front Raise", muscleGroup: "SHOULDERS", category: "Front Deltoid", equipment: "Cable" },
          { id: "smith-machine-shoulder-press", name: "Smith Machine Shoulder Press", muscleGroup: "SHOULDERS", category: "Front Deltoid", equipment: "Machine" },
          { id: "plate-loaded-shoulder-press", name: "Plate-Loaded Shoulder Press", muscleGroup: "SHOULDERS", category: "Front Deltoid", equipment: "Machine" },
          { id: "pike-pushup-shoulders", name: "Pike Push-Up", muscleGroup: "SHOULDERS", category: "Front Deltoid", equipment: "Bodyweight" },
          { id: "handstand-pushup", name: "Handstand Push-Up", muscleGroup: "SHOULDERS", category: "Front Deltoid", equipment: "Bodyweight" },
        ],
      },
      {
        id: "shoulders-side",
        name: "Side Deltoid",
        muscleGroup: "SHOULDERS",
        exercises: [
          { id: "dumbbell-lateral-raise", name: "Dumbbell Lateral Raise", muscleGroup: "SHOULDERS", category: "Side Deltoid", equipment: "Dumbbell" },
          { id: "leaning-lateral-raise", name: "Leaning Lateral Raise", muscleGroup: "SHOULDERS", category: "Side Deltoid", equipment: "Dumbbell" },
          { id: "seated-lateral-raise", name: "Seated Lateral Raise", muscleGroup: "SHOULDERS", category: "Side Deltoid", equipment: "Dumbbell" },
          { id: "one-arm-lateral-raise", name: "One-Arm Lateral Raise", muscleGroup: "SHOULDERS", category: "Side Deltoid", equipment: "Dumbbell" },
          { id: "cable-lateral-raise", name: "Cable Lateral Raise", muscleGroup: "SHOULDERS", category: "Side Deltoid", equipment: "Cable" },
          { id: "single-arm-cable-raise", name: "Single-Arm Cable Raise", muscleGroup: "SHOULDERS", category: "Side Deltoid", equipment: "Cable" },
          { id: "behind-back-cable-raise", name: "Behind-Back Cable Raise", muscleGroup: "SHOULDERS", category: "Side Deltoid", equipment: "Cable" },
          { id: "lateral-raise-machine", name: "Lateral Raise Machine", muscleGroup: "SHOULDERS", category: "Side Deltoid", equipment: "Machine" },
          { id: "upright-row-shoulders", name: "Upright Row", muscleGroup: "SHOULDERS", category: "Side Deltoid", equipment: "Barbell" },
        ],
      },
      {
        id: "shoulders-rear",
        name: "Rear Deltoid",
        muscleGroup: "SHOULDERS",
        exercises: [
          { id: "bent-over-reverse-fly", name: "Bent-Over Reverse Fly", muscleGroup: "SHOULDERS", category: "Rear Deltoid", equipment: "Dumbbell" },
          { id: "rear-delt-row", name: "Rear Delt Row", muscleGroup: "SHOULDERS", category: "Rear Deltoid", equipment: "Dumbbell" },
          { id: "incline-reverse-fly-shoulders", name: "Incline Reverse Fly", muscleGroup: "SHOULDERS", category: "Rear Deltoid", equipment: "Dumbbell" },
          { id: "seated-rear-delt-fly", name: "Seated Rear Delt Fly", muscleGroup: "SHOULDERS", category: "Rear Deltoid", equipment: "Dumbbell" },
          { id: "reverse-cable-fly", name: "Reverse Cable Fly", muscleGroup: "SHOULDERS", category: "Rear Deltoid", equipment: "Cable" },
          { id: "face-pull-shoulders", name: "Face Pull", muscleGroup: "SHOULDERS", category: "Rear Deltoid", equipment: "Cable" },
          { id: "rear-delt-machine-fly-shoulders", name: "Rear Delt Machine Fly", muscleGroup: "SHOULDERS", category: "Rear Deltoid", equipment: "Machine" },
          { id: "high-cable-reverse-fly", name: "High Cable Reverse Fly", muscleGroup: "SHOULDERS", category: "Rear Deltoid", equipment: "Cable" },
          { id: "wide-grip-barbell-row-shoulders", name: "Wide-Grip Barbell Row", muscleGroup: "SHOULDERS", category: "Rear Deltoid", equipment: "Barbell" },
        ],
      },
      {
        id: "shoulders-traps",
        name: "Traps",
        muscleGroup: "SHOULDERS",
        exercises: [
          { id: "barbell-shrug-shoulders", name: "Barbell Shrug", muscleGroup: "SHOULDERS", category: "Traps", equipment: "Barbell" },
          { id: "upright-row-traps", name: "Upright Row", muscleGroup: "SHOULDERS", category: "Traps", equipment: "Barbell" },
          { id: "behind-back-shrug", name: "Behind-the-Back Shrug", muscleGroup: "SHOULDERS", category: "Traps", equipment: "Barbell" },
          { id: "dumbbell-shrug-shoulders", name: "Dumbbell Shrug", muscleGroup: "SHOULDERS", category: "Traps", equipment: "Dumbbell" },
          { id: "dumbbell-upright-row-shoulders", name: "Dumbbell Upright Row", muscleGroup: "SHOULDERS", category: "Traps", equipment: "Dumbbell" },
          { id: "incline-shrug", name: "Incline Shrug", muscleGroup: "SHOULDERS", category: "Traps", equipment: "Dumbbell" },
          { id: "cable-shrug-shoulders", name: "Cable Shrug", muscleGroup: "SHOULDERS", category: "Traps", equipment: "Cable" },
          { id: "machine-shrug", name: "Machine Shrug", muscleGroup: "SHOULDERS", category: "Traps", equipment: "Machine" },
          { id: "smith-machine-shrug", name: "Smith Machine Shrug", muscleGroup: "SHOULDERS", category: "Traps", equipment: "Machine" },
          { id: "scapular-pullup-shoulders", name: "Scapular Pull-Up", muscleGroup: "SHOULDERS", category: "Traps", equipment: "Bodyweight" },
          { id: "weighted-carry", name: "Weighted Carry", muscleGroup: "SHOULDERS", category: "Traps", equipment: "Bodyweight" },
        ],
      },
    ],
  },
  {
    id: "legs",
    name: "LEGS",
    categories: [
      {
        id: "legs-quads",
        name: "Quadriceps",
        muscleGroup: "LEGS",
        exercises: [
          { id: "back-squat", name: "Back Squat", muscleGroup: "LEGS", category: "Quadriceps", equipment: "Barbell" },
          { id: "front-squat", name: "Front Squat", muscleGroup: "LEGS", category: "Quadriceps", equipment: "Barbell" },
          { id: "zercher-squat", name: "Zercher Squat", muscleGroup: "LEGS", category: "Quadriceps", equipment: "Barbell" },
          { id: "hack-squat-barbell", name: "Hack Squat (Barbell)", muscleGroup: "LEGS", category: "Quadriceps", equipment: "Barbell" },
          { id: "goblet-squat", name: "Goblet Squat", muscleGroup: "LEGS", category: "Quadriceps", equipment: "Dumbbell" },
          { id: "dumbbell-bulgarian-split-squat", name: "Dumbbell Bulgarian Split Squat", muscleGroup: "LEGS", category: "Quadriceps", equipment: "Dumbbell" },
          { id: "dumbbell-step-up", name: "Dumbbell Step-Up", muscleGroup: "LEGS", category: "Quadriceps", equipment: "Dumbbell" },
          { id: "dumbbell-lunges", name: "Dumbbell Lunges", muscleGroup: "LEGS", category: "Quadriceps", equipment: "Dumbbell" },
          { id: "leg-press", name: "Leg Press", muscleGroup: "LEGS", category: "Quadriceps", equipment: "Machine" },
          { id: "hack-squat-machine", name: "Hack Squat Machine", muscleGroup: "LEGS", category: "Quadriceps", equipment: "Machine" },
          { id: "leg-extension", name: "Leg Extension", muscleGroup: "LEGS", category: "Quadriceps", equipment: "Machine" },
          { id: "smith-machine-squat", name: "Smith Machine Squat", muscleGroup: "LEGS", category: "Quadriceps", equipment: "Machine" },
          { id: "bodyweight-squat", name: "Bodyweight Squat", muscleGroup: "LEGS", category: "Quadriceps", equipment: "Bodyweight" },
          { id: "jump-squat", name: "Jump Squat", muscleGroup: "LEGS", category: "Quadriceps", equipment: "Bodyweight" },
          { id: "wall-sit", name: "Wall Sit", muscleGroup: "LEGS", category: "Quadriceps", equipment: "Bodyweight" },
          { id: "sissy-squat", name: "Sissy Squat", muscleGroup: "LEGS", category: "Quadriceps", equipment: "Bodyweight" },
          { id: "pistol-squat", name: "Pistol Squat", muscleGroup: "LEGS", category: "Quadriceps", equipment: "Bodyweight" },
        ],
      },
      {
        id: "legs-glutes",
        name: "Glutes",
        muscleGroup: "LEGS",
        exercises: [
          { id: "hip-thrust", name: "Hip Thrust", muscleGroup: "LEGS", category: "Glutes", equipment: "Barbell" },
          { id: "glute-bridge-barbell", name: "Glute Bridge (Barbell)", muscleGroup: "LEGS", category: "Glutes", equipment: "Barbell" },
          { id: "romanian-deadlift", name: "Romanian Deadlift", muscleGroup: "LEGS", category: "Glutes", equipment: "Barbell" },
          { id: "sumo-deadlift", name: "Sumo Deadlift", muscleGroup: "LEGS", category: "Glutes", equipment: "Barbell" },
          { id: "dumbbell-hip-thrust", name: "Dumbbell Hip Thrust", muscleGroup: "LEGS", category: "Glutes", equipment: "Dumbbell" },
          { id: "dumbbell-glute-bridge", name: "Dumbbell Glute Bridge", muscleGroup: "LEGS", category: "Glutes", equipment: "Dumbbell" },
          { id: "dumbbell-step-up-glutes", name: "Dumbbell Step-Up", muscleGroup: "LEGS", category: "Glutes", equipment: "Dumbbell" },
          { id: "dumbbell-walking-lunge", name: "Dumbbell Walking Lunge", muscleGroup: "LEGS", category: "Glutes", equipment: "Dumbbell" },
          { id: "glute-kickback", name: "Glute Kickback", muscleGroup: "LEGS", category: "Glutes", equipment: "Cable" },
          { id: "smith-machine-hip-thrust", name: "Smith Machine Hip Thrust", muscleGroup: "LEGS", category: "Glutes", equipment: "Machine" },
          { id: "cable-pull-through", name: "Cable Pull-Through", muscleGroup: "LEGS", category: "Glutes", equipment: "Cable" },
          { id: "glute-extension-machine", name: "Glute Extension Machine", muscleGroup: "LEGS", category: "Glutes", equipment: "Machine" },
          { id: "glute-bridge-bodyweight", name: "Glute Bridge", muscleGroup: "LEGS", category: "Glutes", equipment: "Bodyweight" },
          { id: "donkey-kick", name: "Donkey Kick", muscleGroup: "LEGS", category: "Glutes", equipment: "Bodyweight" },
          { id: "fire-hydrant", name: "Fire Hydrant", muscleGroup: "LEGS", category: "Glutes", equipment: "Bodyweight" },
          { id: "single-leg-glute-bridge", name: "Single-Leg Glute Bridge", muscleGroup: "LEGS", category: "Glutes", equipment: "Bodyweight" },
          { id: "banded-lateral-walks", name: "Banded Lateral Walks", muscleGroup: "LEGS", category: "Glutes", equipment: "Bodyweight" },
        ],
      },
      {
        id: "legs-hamstrings",
        name: "Hamstrings",
        muscleGroup: "LEGS",
        exercises: [
          { id: "romanian-deadlift-hamstrings", name: "Romanian Deadlift", muscleGroup: "LEGS", category: "Hamstrings", equipment: "Barbell" },
          { id: "stiff-leg-deadlift", name: "Stiff-Leg Deadlift", muscleGroup: "LEGS", category: "Hamstrings", equipment: "Barbell" },
          { id: "good-morning-legs", name: "Good Morning", muscleGroup: "LEGS", category: "Hamstrings", equipment: "Barbell" },
          { id: "barbell-glute-ham-raise", name: "Barbell Glute-Ham Raise", muscleGroup: "LEGS", category: "Hamstrings", equipment: "Barbell" },
          { id: "dumbbell-rdl", name: "Dumbbell RDL", muscleGroup: "LEGS", category: "Hamstrings", equipment: "Dumbbell" },
          { id: "dumbbell-stiff-leg-deadlift", name: "Dumbbell Stiff-Leg Deadlift", muscleGroup: "LEGS", category: "Hamstrings", equipment: "Dumbbell" },
          { id: "dumbbell-step-up-hamstrings", name: "Dumbbell Step-Up", muscleGroup: "LEGS", category: "Hamstrings", equipment: "Dumbbell" },
          { id: "lying-leg-curl", name: "Lying Leg Curl Machine", muscleGroup: "LEGS", category: "Hamstrings", equipment: "Machine" },
          { id: "seated-leg-curl", name: "Seated Leg Curl Machine", muscleGroup: "LEGS", category: "Hamstrings", equipment: "Machine" },
          { id: "standing-leg-curl", name: "Standing Leg Curl Machine", muscleGroup: "LEGS", category: "Hamstrings", equipment: "Machine" },
          { id: "cable-kickback-hamstrings", name: "Cable Kickback", muscleGroup: "LEGS", category: "Hamstrings", equipment: "Cable" },
          { id: "glute-ham-raise", name: "Glute-Ham Raise", muscleGroup: "LEGS", category: "Hamstrings", equipment: "Bodyweight" },
          { id: "nordic-hamstring-curl", name: "Nordic Hamstring Curl", muscleGroup: "LEGS", category: "Hamstrings", equipment: "Bodyweight" },
          { id: "sliding-leg-curl", name: "Sliding Leg Curl", muscleGroup: "LEGS", category: "Hamstrings", equipment: "Bodyweight" },
        ],
      },
      {
        id: "legs-calves",
        name: "Calves",
        muscleGroup: "LEGS",
        exercises: [
          { id: "standing-calf-raise-barbell", name: "Standing Calf Raise (Barbell)", muscleGroup: "LEGS", category: "Calves", equipment: "Barbell" },
          { id: "seated-barbell-calf-raise", name: "Seated Barbell Calf Raise", muscleGroup: "LEGS", category: "Calves", equipment: "Barbell" },
          { id: "dumbbell-calf-raise", name: "Dumbbell Calf Raise", muscleGroup: "LEGS", category: "Calves", equipment: "Dumbbell" },
          { id: "single-leg-dumbbell-calf-raise", name: "Single-Leg Dumbbell Calf Raise", muscleGroup: "LEGS", category: "Calves", equipment: "Dumbbell" },
          { id: "standing-calf-raise-machine", name: "Standing Calf Raise Machine", muscleGroup: "LEGS", category: "Calves", equipment: "Machine" },
          { id: "seated-calf-raise-machine", name: "Seated Calf Raise Machine", muscleGroup: "LEGS", category: "Calves", equipment: "Machine" },
          { id: "leg-press-calf-raise", name: "Leg Press Calf Raise", muscleGroup: "LEGS", category: "Calves", equipment: "Machine" },
          { id: "standing-calf-raise-bodyweight", name: "Standing Calf Raise", muscleGroup: "LEGS", category: "Calves", equipment: "Bodyweight" },
          { id: "single-leg-calf-raise", name: "Single-Leg Calf Raise", muscleGroup: "LEGS", category: "Calves", equipment: "Bodyweight" },
          { id: "tip-toe-hold", name: "Tip-Toe Hold", muscleGroup: "LEGS", category: "Calves", equipment: "Bodyweight" },
          { id: "jump-rope", name: "Jump Rope", muscleGroup: "LEGS", category: "Calves", equipment: "Bodyweight" },
        ],
      },
      {
        id: "legs-inner-thigh",
        name: "Inner Thigh (Adductors)",
        muscleGroup: "LEGS",
        exercises: [
          { id: "cable-adduction", name: "Cable Adduction", muscleGroup: "LEGS", category: "Inner Thigh", equipment: "Cable" },
          { id: "dumbbell-side-lunge", name: "Dumbbell Side Lunge", muscleGroup: "LEGS", category: "Inner Thigh", equipment: "Dumbbell" },
          { id: "cossack-squat", name: "Cossack Squat", muscleGroup: "LEGS", category: "Inner Thigh", equipment: "Dumbbell" },
          { id: "seated-hip-adduction-machine", name: "Seated Hip Adduction Machine", muscleGroup: "LEGS", category: "Inner Thigh", equipment: "Machine" },
          { id: "side-lunge", name: "Side Lunge", muscleGroup: "LEGS", category: "Inner Thigh", equipment: "Bodyweight" },
          { id: "copenhagen-plank", name: "Copenhagen Plank", muscleGroup: "LEGS", category: "Inner Thigh", equipment: "Bodyweight" },
        ],
      },
      {
        id: "legs-outer-thigh",
        name: "Outer Thigh (Abductors)",
        muscleGroup: "LEGS",
        exercises: [
          { id: "banded-lateral-walk", name: "Banded Lateral Walk", muscleGroup: "LEGS", category: "Outer Thigh", equipment: "Bodyweight" },
          { id: "dumbbell-curtsy-lunge", name: "Dumbbell Curtsy Lunge", muscleGroup: "LEGS", category: "Outer Thigh", equipment: "Dumbbell" },
          { id: "banded-clamshell", name: "Banded Clamshell", muscleGroup: "LEGS", category: "Outer Thigh", equipment: "Bodyweight" },
          { id: "side-lying-leg-raise", name: "Side-Lying Leg Raise", muscleGroup: "LEGS", category: "Outer Thigh", equipment: "Bodyweight" },
          { id: "seated-hip-abduction-machine", name: "Seated Hip Abduction Machine", muscleGroup: "LEGS", category: "Outer Thigh", equipment: "Machine" },
          { id: "standing-hip-abduction-machine", name: "Standing Hip Abduction Machine", muscleGroup: "LEGS", category: "Outer Thigh", equipment: "Machine" },
          { id: "cable-hip-abduction", name: "Cable Hip Abduction", muscleGroup: "LEGS", category: "Outer Thigh", equipment: "Cable" },
          { id: "side-plank-leg-lift", name: "Side Plank + Leg Lift", muscleGroup: "LEGS", category: "Outer Thigh", equipment: "Bodyweight" },
          { id: "fire-hydrant-outer-thigh", name: "Fire Hydrant", muscleGroup: "LEGS", category: "Outer Thigh", equipment: "Bodyweight" },
        ],
      },
    ],
  },
  {
    id: "core",
    name: "CORE",
    categories: [
      {
        id: "core-upper-abs",
        name: "Upper Abs",
        muscleGroup: "CORE",
        exercises: [
          { id: "crunch", name: "Crunch", muscleGroup: "CORE", category: "Upper Abs", equipment: "Bodyweight" },
          { id: "cable-crunch", name: "Cable Crunch", muscleGroup: "CORE", category: "Upper Abs", equipment: "Cable" },
          { id: "ab-wheel-rollout", name: "Ab Wheel Rollout", muscleGroup: "CORE", category: "Upper Abs", equipment: "Bodyweight" },
          { id: "decline-crunch", name: "Decline Crunch", muscleGroup: "CORE", category: "Upper Abs", equipment: "Bodyweight" },
          { id: "weighted-crunch", name: "Weighted Crunch", muscleGroup: "CORE", category: "Upper Abs", equipment: "Dumbbell" },
          { id: "machine-crunch", name: "Machine Crunch", muscleGroup: "CORE", category: "Upper Abs", equipment: "Machine" },
          { id: "ball-crunch", name: "Exercise Ball Crunch", muscleGroup: "CORE", category: "Upper Abs", equipment: "Bodyweight" },
          { id: "rope-crunch", name: "Rope Crunch (Kneeling)", muscleGroup: "CORE", category: "Upper Abs", equipment: "Cable" },
          { id: "v-up", name: "V-Up", muscleGroup: "CORE", category: "Upper Abs", equipment: "Bodyweight" },
          { id: "sit-up", name: "Sit-Up", muscleGroup: "CORE", category: "Upper Abs", equipment: "Bodyweight" },
          { id: "decline-sit-up", name: "Decline Sit-Up", muscleGroup: "CORE", category: "Upper Abs", equipment: "Bodyweight" },
        ],
      },
      {
        id: "core-lower-abs",
        name: "Lower Abs",
        muscleGroup: "CORE",
        exercises: [
          { id: "leg-raise", name: "Leg Raise", muscleGroup: "CORE", category: "Lower Abs", equipment: "Bodyweight" },
          { id: "hanging-leg-raise", name: "Hanging Leg Raise", muscleGroup: "CORE", category: "Lower Abs", equipment: "Bodyweight" },
          { id: "hanging-knee-raise", name: "Hanging Knee Raise", muscleGroup: "CORE", category: "Lower Abs", equipment: "Bodyweight" },
          { id: "reverse-crunch", name: "Reverse Crunch", muscleGroup: "CORE", category: "Lower Abs", equipment: "Bodyweight" },
          { id: "decline-reverse-crunch", name: "Decline Reverse Crunch", muscleGroup: "CORE", category: "Lower Abs", equipment: "Bodyweight" },
          { id: "captain-chair-leg-raise", name: "Captain's Chair Leg Raise", muscleGroup: "CORE", category: "Lower Abs", equipment: "Machine" },
          { id: "lying-leg-raise", name: "Lying Leg Raise", muscleGroup: "CORE", category: "Lower Abs", equipment: "Bodyweight" },
          { id: "flutter-kicks", name: "Flutter Kicks", muscleGroup: "CORE", category: "Lower Abs", equipment: "Bodyweight" },
          { id: "scissor-kicks", name: "Scissor Kicks", muscleGroup: "CORE", category: "Lower Abs", equipment: "Bodyweight" },
          { id: "mountain-climbers", name: "Mountain Climbers", muscleGroup: "CORE", category: "Lower Abs", equipment: "Bodyweight" },
          { id: "knee-tucks", name: "Knee Tucks", muscleGroup: "CORE", category: "Lower Abs", equipment: "Bodyweight" },
          { id: "cable-knee-raise", name: "Cable Knee Raise", muscleGroup: "CORE", category: "Lower Abs", equipment: "Cable" },
        ],
      },
      {
        id: "core-obliques",
        name: "Obliques",
        muscleGroup: "CORE",
        exercises: [
          { id: "russian-twist", name: "Russian Twist", muscleGroup: "CORE", category: "Obliques", equipment: "Bodyweight" },
          { id: "weighted-russian-twist", name: "Weighted Russian Twist", muscleGroup: "CORE", category: "Obliques", equipment: "Dumbbell" },
          { id: "side-plank", name: "Side Plank", muscleGroup: "CORE", category: "Obliques", equipment: "Bodyweight" },
          { id: "side-plank-dips", name: "Side Plank Dips", muscleGroup: "CORE", category: "Obliques", equipment: "Bodyweight" },
          { id: "oblique-crunch", name: "Oblique Crunch", muscleGroup: "CORE", category: "Obliques", equipment: "Bodyweight" },
          { id: "bicycle-crunch", name: "Bicycle Crunch", muscleGroup: "CORE", category: "Obliques", equipment: "Bodyweight" },
          { id: "heel-touches", name: "Heel Touches", muscleGroup: "CORE", category: "Obliques", equipment: "Bodyweight" },
          { id: "side-bend-dumbbell", name: "Dumbbell Side Bend", muscleGroup: "CORE", category: "Obliques", equipment: "Dumbbell" },
          { id: "cable-wood-chop", name: "Cable Wood Chop", muscleGroup: "CORE", category: "Obliques", equipment: "Cable" },
          { id: "cable-oblique-crunch", name: "Cable Oblique Crunch", muscleGroup: "CORE", category: "Obliques", equipment: "Cable" },
          { id: "landmine-rotation", name: "Landmine Rotation", muscleGroup: "CORE", category: "Obliques", equipment: "Barbell" },
          { id: "hanging-oblique-raise", name: "Hanging Oblique Raise", muscleGroup: "CORE", category: "Obliques", equipment: "Bodyweight" },
          { id: "windshield-wipers", name: "Windshield Wipers", muscleGroup: "CORE", category: "Obliques", equipment: "Bodyweight" },
          { id: "side-jackknife", name: "Side Jackknife", muscleGroup: "CORE", category: "Obliques", equipment: "Bodyweight" },
          { id: "suitcase-carry", name: "Suitcase Carry", muscleGroup: "CORE", category: "Obliques", equipment: "Dumbbell" },
        ],
      },
      {
        id: "core-full-core",
        name: "Full Core",
        muscleGroup: "CORE",
        exercises: [
          { id: "plank", name: "Plank", muscleGroup: "CORE", category: "Full Core", equipment: "Bodyweight" },
          { id: "weighted-plank", name: "Weighted Plank", muscleGroup: "CORE", category: "Full Core", equipment: "Bodyweight" },
          { id: "rkg-plank", name: "RKG Plank", muscleGroup: "CORE", category: "Full Core", equipment: "Bodyweight" },
          { id: "plank-up-down", name: "Plank Up-Down", muscleGroup: "CORE", category: "Full Core", equipment: "Bodyweight" },
          { id: "plank-shoulder-taps", name: "Plank Shoulder Taps", muscleGroup: "CORE", category: "Full Core", equipment: "Bodyweight" },
          { id: "hollow-body-hold", name: "Hollow Body Hold", muscleGroup: "CORE", category: "Full Core", equipment: "Bodyweight" },
          { id: "dead-bug", name: "Dead Bug", muscleGroup: "CORE", category: "Full Core", equipment: "Bodyweight" },
          { id: "bird-dog-core", name: "Bird Dog", muscleGroup: "CORE", category: "Full Core", equipment: "Bodyweight" },
          { id: "dragon-flag", name: "Dragon Flag", muscleGroup: "CORE", category: "Full Core", equipment: "Bodyweight" },
          { id: "l-sit", name: "L-Sit", muscleGroup: "CORE", category: "Full Core", equipment: "Bodyweight" },
          { id: "toes-to-bar", name: "Toes to Bar", muscleGroup: "CORE", category: "Full Core", equipment: "Bodyweight" },
          { id: "turkish-get-up", name: "Turkish Get-Up", muscleGroup: "CORE", category: "Full Core", equipment: "Dumbbell" },
          { id: "farmers-walk", name: "Farmer's Walk", muscleGroup: "CORE", category: "Full Core", equipment: "Dumbbell" },
          { id: "barbell-rollout", name: "Barbell Rollout", muscleGroup: "CORE", category: "Full Core", equipment: "Barbell" },
          { id: "pallof-press", name: "Pallof Press", muscleGroup: "CORE", category: "Full Core", equipment: "Cable" },
          { id: "cable-rotation", name: "Cable Rotation", muscleGroup: "CORE", category: "Full Core", equipment: "Cable" },
        ],
      },
      {
        id: "core-lower-back",
        name: "Lower Back (Erectors)",
        muscleGroup: "CORE",
        exercises: [
          { id: "back-extension", name: "Back Extension", muscleGroup: "CORE", category: "Lower Back", equipment: "Bodyweight" },
          { id: "weighted-back-extension", name: "Weighted Back Extension", muscleGroup: "CORE", category: "Lower Back", equipment: "Dumbbell" },
          { id: "superman", name: "Superman", muscleGroup: "CORE", category: "Lower Back", equipment: "Bodyweight" },
          { id: "good-morning-core", name: "Good Morning", muscleGroup: "CORE", category: "Lower Back", equipment: "Barbell" },
          { id: "hyperextension-core", name: "Hyperextension", muscleGroup: "CORE", category: "Lower Back", equipment: "Machine" },
          { id: "reverse-hyperextension-core", name: "Reverse Hyperextension", muscleGroup: "CORE", category: "Lower Back", equipment: "Machine" },
          { id: "bird-dog-lower-back", name: "Bird Dog", muscleGroup: "CORE", category: "Lower Back", equipment: "Bodyweight" },
          { id: "romanian-deadlift-core", name: "Romanian Deadlift", muscleGroup: "CORE", category: "Lower Back", equipment: "Barbell" },
          { id: "deadlift-core", name: "Deadlift", muscleGroup: "CORE", category: "Lower Back", equipment: "Barbell" },
        ],
      },
    ],
  },
  {
    id: "warmup",
    name: "WARMUP",
    categories: [
      {
        id: "warmup-cardio",
        name: "Cardio Warmup",
        muscleGroup: "WARMUP",
        exercises: [
          { id: "jumping-jacks", name: "Jumping Jacks", muscleGroup: "WARMUP", category: "Cardio Warmup", equipment: "Bodyweight" },
          { id: "high-knees", name: "High Knees", muscleGroup: "WARMUP", category: "Cardio Warmup", equipment: "Bodyweight" },
          { id: "butt-kicks", name: "Butt Kicks", muscleGroup: "WARMUP", category: "Cardio Warmup", equipment: "Bodyweight" },
          { id: "jumping-rope-warmup", name: "Jump Rope", muscleGroup: "WARMUP", category: "Cardio Warmup", equipment: "Bodyweight" },
          { id: "burpees", name: "Burpees", muscleGroup: "WARMUP", category: "Cardio Warmup", equipment: "Bodyweight" },
          { id: "mountain-climbers-warmup", name: "Mountain Climbers", muscleGroup: "WARMUP", category: "Cardio Warmup", equipment: "Bodyweight" },
          { id: "fast-feet", name: "Fast Feet", muscleGroup: "WARMUP", category: "Cardio Warmup", equipment: "Bodyweight" },
          { id: "skaters", name: "Skaters", muscleGroup: "WARMUP", category: "Cardio Warmup", equipment: "Bodyweight" },
          { id: "side-shuffles", name: "Side Shuffles", muscleGroup: "WARMUP", category: "Cardio Warmup", equipment: "Bodyweight" },
          { id: "light-jog", name: "Light Jog", muscleGroup: "WARMUP", category: "Cardio Warmup", equipment: "Bodyweight" },
          { id: "march-in-place", name: "March in Place", muscleGroup: "WARMUP", category: "Cardio Warmup", equipment: "Bodyweight" },
        ],
      },
      {
        id: "warmup-dynamic",
        name: "Dynamic Stretches",
        muscleGroup: "WARMUP",
        exercises: [
          { id: "arm-circles", name: "Arm Circles", muscleGroup: "WARMUP", category: "Dynamic Stretches", equipment: "Bodyweight" },
          { id: "leg-swings-forward", name: "Leg Swings (Forward/Back)", muscleGroup: "WARMUP", category: "Dynamic Stretches", equipment: "Bodyweight" },
          { id: "leg-swings-side", name: "Leg Swings (Side to Side)", muscleGroup: "WARMUP", category: "Dynamic Stretches", equipment: "Bodyweight" },
          { id: "hip-circles", name: "Hip Circles", muscleGroup: "WARMUP", category: "Dynamic Stretches", equipment: "Bodyweight" },
          { id: "torso-twists", name: "Torso Twists", muscleGroup: "WARMUP", category: "Dynamic Stretches", equipment: "Bodyweight" },
          { id: "walking-lunges", name: "Walking Lunges", muscleGroup: "WARMUP", category: "Dynamic Stretches", equipment: "Bodyweight" },
          { id: "frankenstein-walks", name: "Frankenstein Walks", muscleGroup: "WARMUP", category: "Dynamic Stretches", equipment: "Bodyweight" },
          { id: "inchworms", name: "Inchworms", muscleGroup: "WARMUP", category: "Dynamic Stretches", equipment: "Bodyweight" },
          { id: "world-greatest-stretch", name: "World's Greatest Stretch", muscleGroup: "WARMUP", category: "Dynamic Stretches", equipment: "Bodyweight" },
          { id: "cat-cow-stretch", name: "Cat-Cow Stretch", muscleGroup: "WARMUP", category: "Dynamic Stretches", equipment: "Bodyweight" },
          { id: "spiderman-stretch", name: "Spiderman Stretch", muscleGroup: "WARMUP", category: "Dynamic Stretches", equipment: "Bodyweight" },
          { id: "scorpion-stretch", name: "Scorpion Stretch", muscleGroup: "WARMUP", category: "Dynamic Stretches", equipment: "Bodyweight" },
          { id: "fire-hydrants-warmup", name: "Fire Hydrants", muscleGroup: "WARMUP", category: "Dynamic Stretches", equipment: "Bodyweight" },
        ],
      },
      {
        id: "warmup-activation",
        name: "Muscle Activation",
        muscleGroup: "WARMUP",
        exercises: [
          { id: "band-pull-aparts", name: "Band Pull-Aparts", muscleGroup: "WARMUP", category: "Muscle Activation", equipment: "Bodyweight" },
          { id: "glute-bridges-warmup", name: "Glute Bridges", muscleGroup: "WARMUP", category: "Muscle Activation", equipment: "Bodyweight" },
          { id: "clamshells", name: "Clamshells", muscleGroup: "WARMUP", category: "Muscle Activation", equipment: "Bodyweight" },
          { id: "band-walks", name: "Band Walks", muscleGroup: "WARMUP", category: "Muscle Activation", equipment: "Bodyweight" },
          { id: "scapular-wall-slides", name: "Scapular Wall Slides", muscleGroup: "WARMUP", category: "Muscle Activation", equipment: "Bodyweight" },
          { id: "bird-dogs-warmup", name: "Bird Dogs", muscleGroup: "WARMUP", category: "Muscle Activation", equipment: "Bodyweight" },
          { id: "dead-bugs-warmup", name: "Dead Bugs", muscleGroup: "WARMUP", category: "Muscle Activation", equipment: "Bodyweight" },
          { id: "push-up-plus", name: "Push-Up Plus", muscleGroup: "WARMUP", category: "Muscle Activation", equipment: "Bodyweight" },
          { id: "plank-to-downdog", name: "Plank to Down Dog", muscleGroup: "WARMUP", category: "Muscle Activation", equipment: "Bodyweight" },
          { id: "wall-angels-warmup", name: "Wall Angels", muscleGroup: "WARMUP", category: "Muscle Activation", equipment: "Bodyweight" },
        ],
      },
      {
        id: "warmup-mobility",
        name: "Joint Mobility",
        muscleGroup: "WARMUP",
        exercises: [
          { id: "ankle-circles", name: "Ankle Circles", muscleGroup: "WARMUP", category: "Joint Mobility", equipment: "Bodyweight" },
          { id: "wrist-circles", name: "Wrist Circles", muscleGroup: "WARMUP", category: "Joint Mobility", equipment: "Bodyweight" },
          { id: "shoulder-dislocations", name: "Shoulder Dislocations", muscleGroup: "WARMUP", category: "Joint Mobility", equipment: "Bodyweight" },
          { id: "neck-rolls", name: "Neck Rolls", muscleGroup: "WARMUP", category: "Joint Mobility", equipment: "Bodyweight" },
          { id: "hip-openers", name: "Hip Openers", muscleGroup: "WARMUP", category: "Joint Mobility", equipment: "Bodyweight" },
          { id: "90-90-hip-stretch", name: "90/90 Hip Stretch", muscleGroup: "WARMUP", category: "Joint Mobility", equipment: "Bodyweight" },
          { id: "deep-squat-hold", name: "Deep Squat Hold", muscleGroup: "WARMUP", category: "Joint Mobility", equipment: "Bodyweight" },
          { id: "t-spine-rotations", name: "T-Spine Rotations", muscleGroup: "WARMUP", category: "Joint Mobility", equipment: "Bodyweight" },
          { id: "thread-the-needle", name: "Thread the Needle", muscleGroup: "WARMUP", category: "Joint Mobility", equipment: "Bodyweight" },
        ],
      },
    ],
  },
  {
    id: "stretching",
    name: "STRETCHING",
    categories: [
      {
        id: "stretch-chest",
        name: "Chest Stretches",
        muscleGroup: "STRETCHING",
        exercises: [
          { id: "doorway-chest-stretch", name: "Doorway Chest Stretch", muscleGroup: "STRETCHING", category: "Chest Stretches", equipment: "Bodyweight" },
          { id: "corner-chest-stretch", name: "Corner Chest Stretch", muscleGroup: "STRETCHING", category: "Chest Stretches", equipment: "Bodyweight" },
          { id: "wall-chest-stretch", name: "Wall Chest Stretch", muscleGroup: "STRETCHING", category: "Chest Stretches", equipment: "Bodyweight" },
          { id: "lying-chest-stretch", name: "Lying Chest Stretch", muscleGroup: "STRETCHING", category: "Chest Stretches", equipment: "Bodyweight" },
          { id: "behind-back-clasp", name: "Behind Back Clasp Stretch", muscleGroup: "STRETCHING", category: "Chest Stretches", equipment: "Bodyweight" },
        ],
      },
      {
        id: "stretch-back",
        name: "Back Stretches",
        muscleGroup: "STRETCHING",
        exercises: [
          { id: "childs-pose", name: "Child's Pose", muscleGroup: "STRETCHING", category: "Back Stretches", equipment: "Bodyweight" },
          { id: "cat-cow-stretch-back", name: "Cat-Cow Stretch", muscleGroup: "STRETCHING", category: "Back Stretches", equipment: "Bodyweight" },
          { id: "cobra-stretch", name: "Cobra Stretch", muscleGroup: "STRETCHING", category: "Back Stretches", equipment: "Bodyweight" },
          { id: "seated-spinal-twist", name: "Seated Spinal Twist", muscleGroup: "STRETCHING", category: "Back Stretches", equipment: "Bodyweight" },
          { id: "knee-to-chest-stretch", name: "Knee to Chest Stretch", muscleGroup: "STRETCHING", category: "Back Stretches", equipment: "Bodyweight" },
          { id: "supine-twist", name: "Supine Twist", muscleGroup: "STRETCHING", category: "Back Stretches", equipment: "Bodyweight" },
          { id: "downward-dog", name: "Downward Dog", muscleGroup: "STRETCHING", category: "Back Stretches", equipment: "Bodyweight" },
          { id: "lat-stretch-overhead", name: "Lat Stretch (Overhead)", muscleGroup: "STRETCHING", category: "Back Stretches", equipment: "Bodyweight" },
          { id: "lat-stretch-side-bend", name: "Lat Stretch (Side Bend)", muscleGroup: "STRETCHING", category: "Back Stretches", equipment: "Bodyweight" },
        ],
      },
      {
        id: "stretch-shoulders",
        name: "Shoulder Stretches",
        muscleGroup: "STRETCHING",
        exercises: [
          { id: "cross-body-shoulder-stretch", name: "Cross-Body Shoulder Stretch", muscleGroup: "STRETCHING", category: "Shoulder Stretches", equipment: "Bodyweight" },
          { id: "overhead-tricep-stretch", name: "Overhead Tricep Stretch", muscleGroup: "STRETCHING", category: "Shoulder Stretches", equipment: "Bodyweight" },
          { id: "sleeper-stretch", name: "Sleeper Stretch", muscleGroup: "STRETCHING", category: "Shoulder Stretches", equipment: "Bodyweight" },
          { id: "thread-needle-stretch", name: "Thread the Needle", muscleGroup: "STRETCHING", category: "Shoulder Stretches", equipment: "Bodyweight" },
          { id: "reverse-prayer-pose", name: "Reverse Prayer Pose", muscleGroup: "STRETCHING", category: "Shoulder Stretches", equipment: "Bodyweight" },
          { id: "shoulder-rolls", name: "Shoulder Rolls", muscleGroup: "STRETCHING", category: "Shoulder Stretches", equipment: "Bodyweight" },
          { id: "eagle-arms", name: "Eagle Arms", muscleGroup: "STRETCHING", category: "Shoulder Stretches", equipment: "Bodyweight" },
        ],
      },
      {
        id: "stretch-arms",
        name: "Arm Stretches",
        muscleGroup: "STRETCHING",
        exercises: [
          { id: "bicep-stretch-wall", name: "Bicep Wall Stretch", muscleGroup: "STRETCHING", category: "Arm Stretches", equipment: "Bodyweight" },
          { id: "tricep-overhead-stretch", name: "Tricep Overhead Stretch", muscleGroup: "STRETCHING", category: "Arm Stretches", equipment: "Bodyweight" },
          { id: "forearm-flexor-stretch", name: "Forearm Flexor Stretch", muscleGroup: "STRETCHING", category: "Arm Stretches", equipment: "Bodyweight" },
          { id: "forearm-extensor-stretch", name: "Forearm Extensor Stretch", muscleGroup: "STRETCHING", category: "Arm Stretches", equipment: "Bodyweight" },
          { id: "wrist-flexor-stretch", name: "Wrist Flexor Stretch", muscleGroup: "STRETCHING", category: "Arm Stretches", equipment: "Bodyweight" },
          { id: "wrist-extensor-stretch", name: "Wrist Extensor Stretch", muscleGroup: "STRETCHING", category: "Arm Stretches", equipment: "Bodyweight" },
          { id: "prayer-pose-wrist", name: "Prayer Pose (Wrist)", muscleGroup: "STRETCHING", category: "Arm Stretches", equipment: "Bodyweight" },
        ],
      },
      {
        id: "stretch-legs",
        name: "Leg Stretches",
        muscleGroup: "STRETCHING",
        exercises: [
          { id: "standing-quad-stretch", name: "Standing Quad Stretch", muscleGroup: "STRETCHING", category: "Leg Stretches", equipment: "Bodyweight" },
          { id: "kneeling-hip-flexor-stretch", name: "Kneeling Hip Flexor Stretch", muscleGroup: "STRETCHING", category: "Leg Stretches", equipment: "Bodyweight" },
          { id: "standing-hamstring-stretch", name: "Standing Hamstring Stretch", muscleGroup: "STRETCHING", category: "Leg Stretches", equipment: "Bodyweight" },
          { id: "seated-hamstring-stretch", name: "Seated Hamstring Stretch", muscleGroup: "STRETCHING", category: "Leg Stretches", equipment: "Bodyweight" },
          { id: "pigeon-pose", name: "Pigeon Pose", muscleGroup: "STRETCHING", category: "Leg Stretches", equipment: "Bodyweight" },
          { id: "figure-4-stretch", name: "Figure 4 Stretch", muscleGroup: "STRETCHING", category: "Leg Stretches", equipment: "Bodyweight" },
          { id: "butterfly-stretch", name: "Butterfly Stretch", muscleGroup: "STRETCHING", category: "Leg Stretches", equipment: "Bodyweight" },
          { id: "frog-stretch", name: "Frog Stretch", muscleGroup: "STRETCHING", category: "Leg Stretches", equipment: "Bodyweight" },
          { id: "calf-stretch-wall", name: "Calf Stretch (Wall)", muscleGroup: "STRETCHING", category: "Leg Stretches", equipment: "Bodyweight" },
          { id: "downward-dog-calf", name: "Downward Dog (Calf Focus)", muscleGroup: "STRETCHING", category: "Leg Stretches", equipment: "Bodyweight" },
          { id: "standing-calf-stretch", name: "Standing Calf Stretch", muscleGroup: "STRETCHING", category: "Leg Stretches", equipment: "Bodyweight" },
          { id: "lizard-pose", name: "Lizard Pose", muscleGroup: "STRETCHING", category: "Leg Stretches", equipment: "Bodyweight" },
        ],
      },
      {
        id: "stretch-hips",
        name: "Hip Stretches",
        muscleGroup: "STRETCHING",
        exercises: [
          { id: "hip-flexor-lunge", name: "Hip Flexor Lunge Stretch", muscleGroup: "STRETCHING", category: "Hip Stretches", equipment: "Bodyweight" },
          { id: "90-90-stretch", name: "90/90 Hip Stretch", muscleGroup: "STRETCHING", category: "Hip Stretches", equipment: "Bodyweight" },
          { id: "pigeon-pose-hip", name: "Pigeon Pose", muscleGroup: "STRETCHING", category: "Hip Stretches", equipment: "Bodyweight" },
          { id: "fire-log-pose", name: "Fire Log Pose", muscleGroup: "STRETCHING", category: "Hip Stretches", equipment: "Bodyweight" },
          { id: "happy-baby-pose", name: "Happy Baby Pose", muscleGroup: "STRETCHING", category: "Hip Stretches", equipment: "Bodyweight" },
          { id: "supine-figure-4", name: "Supine Figure 4", muscleGroup: "STRETCHING", category: "Hip Stretches", equipment: "Bodyweight" },
          { id: "seated-hip-stretch", name: "Seated Hip Stretch", muscleGroup: "STRETCHING", category: "Hip Stretches", equipment: "Bodyweight" },
          { id: "pretzel-stretch", name: "Pretzel Stretch", muscleGroup: "STRETCHING", category: "Hip Stretches", equipment: "Bodyweight" },
          { id: "deep-squat-hip", name: "Deep Squat Hold", muscleGroup: "STRETCHING", category: "Hip Stretches", equipment: "Bodyweight" },
        ],
      },
      {
        id: "stretch-full-body",
        name: "Full Body Stretches",
        muscleGroup: "STRETCHING",
        exercises: [
          { id: "standing-forward-fold", name: "Standing Forward Fold", muscleGroup: "STRETCHING", category: "Full Body Stretches", equipment: "Bodyweight" },
          { id: "worlds-greatest-stretch-full", name: "World's Greatest Stretch", muscleGroup: "STRETCHING", category: "Full Body Stretches", equipment: "Bodyweight" },
          { id: "sun-salutation", name: "Sun Salutation", muscleGroup: "STRETCHING", category: "Full Body Stretches", equipment: "Bodyweight" },
          { id: "standing-side-bend", name: "Standing Side Bend", muscleGroup: "STRETCHING", category: "Full Body Stretches", equipment: "Bodyweight" },
          { id: "lying-spinal-twist", name: "Lying Spinal Twist", muscleGroup: "STRETCHING", category: "Full Body Stretches", equipment: "Bodyweight" },
          { id: "seated-forward-fold", name: "Seated Forward Fold", muscleGroup: "STRETCHING", category: "Full Body Stretches", equipment: "Bodyweight" },
          { id: "bridge-pose", name: "Bridge Pose", muscleGroup: "STRETCHING", category: "Full Body Stretches", equipment: "Bodyweight" },
          { id: "savasana", name: "Savasana (Corpse Pose)", muscleGroup: "STRETCHING", category: "Full Body Stretches", equipment: "Bodyweight" },
        ],
      },
    ],
  },
  {
    id: "calisthenics",
    name: "CALISTHENICS",
    categories: [
      {
        id: "calisthenics-push",
        name: "Push Movements",
        muscleGroup: "CALISTHENICS",
        exercises: [
          { id: "push-up", name: "Push-Up", muscleGroup: "CALISTHENICS", category: "Push Movements", equipment: "Bodyweight" },
          { id: "wide-pushup-calisthenics", name: "Wide Push-Up", muscleGroup: "CALISTHENICS", category: "Push Movements", equipment: "Bodyweight" },
          { id: "diamond-pushup-calisthenics", name: "Diamond Push-Up", muscleGroup: "CALISTHENICS", category: "Push Movements", equipment: "Bodyweight" },
          { id: "archer-pushup", name: "Archer Push-Up", muscleGroup: "CALISTHENICS", category: "Push Movements", equipment: "Bodyweight" },
          { id: "decline-pushup-calisthenics", name: "Decline Push-Up", muscleGroup: "CALISTHENICS", category: "Push Movements", equipment: "Bodyweight" },
          { id: "incline-pushup-calisthenics", name: "Incline Push-Up", muscleGroup: "CALISTHENICS", category: "Push Movements", equipment: "Bodyweight" },
          { id: "pike-pushup-calisthenics", name: "Pike Push-Up", muscleGroup: "CALISTHENICS", category: "Push Movements", equipment: "Bodyweight" },
          { id: "pseudo-planche-pushup", name: "Pseudo Planche Push-Up", muscleGroup: "CALISTHENICS", category: "Push Movements", equipment: "Bodyweight" },
          { id: "one-arm-pushup", name: "One-Arm Push-Up", muscleGroup: "CALISTHENICS", category: "Push Movements", equipment: "Bodyweight" },
          { id: "handstand-pushup-calisthenics", name: "Handstand Push-Up", muscleGroup: "CALISTHENICS", category: "Push Movements", equipment: "Bodyweight" },
          { id: "wall-handstand-pushup", name: "Wall Handstand Push-Up", muscleGroup: "CALISTHENICS", category: "Push Movements", equipment: "Bodyweight" },
          { id: "dips-calisthenics", name: "Dips", muscleGroup: "CALISTHENICS", category: "Push Movements", equipment: "Bodyweight" },
          { id: "ring-dips", name: "Ring Dips", muscleGroup: "CALISTHENICS", category: "Push Movements", equipment: "Bodyweight" },
          { id: "korean-dips", name: "Korean Dips", muscleGroup: "CALISTHENICS", category: "Push Movements", equipment: "Bodyweight" },
        ],
      },
      {
        id: "calisthenics-pull",
        name: "Pull Movements",
        muscleGroup: "CALISTHENICS",
        exercises: [
          { id: "pull-up-calisthenics", name: "Pull-Up", muscleGroup: "CALISTHENICS", category: "Pull Movements", equipment: "Bodyweight" },
          { id: "chin-up-calisthenics", name: "Chin-Up", muscleGroup: "CALISTHENICS", category: "Pull Movements", equipment: "Bodyweight" },
          { id: "wide-grip-pullup", name: "Wide-Grip Pull-Up", muscleGroup: "CALISTHENICS", category: "Pull Movements", equipment: "Bodyweight" },
          { id: "close-grip-pullup", name: "Close-Grip Pull-Up", muscleGroup: "CALISTHENICS", category: "Pull Movements", equipment: "Bodyweight" },
          { id: "neutral-grip-pullup-calisthenics", name: "Neutral Grip Pull-Up", muscleGroup: "CALISTHENICS", category: "Pull Movements", equipment: "Bodyweight" },
          { id: "archer-pullup", name: "Archer Pull-Up", muscleGroup: "CALISTHENICS", category: "Pull Movements", equipment: "Bodyweight" },
          { id: "typewriter-pullup", name: "Typewriter Pull-Up", muscleGroup: "CALISTHENICS", category: "Pull Movements", equipment: "Bodyweight" },
          { id: "one-arm-pullup", name: "One-Arm Pull-Up", muscleGroup: "CALISTHENICS", category: "Pull Movements", equipment: "Bodyweight" },
          { id: "commando-pullup", name: "Commando Pull-Up", muscleGroup: "CALISTHENICS", category: "Pull Movements", equipment: "Bodyweight" },
          { id: "muscle-up", name: "Muscle-Up", muscleGroup: "CALISTHENICS", category: "Pull Movements", equipment: "Bodyweight" },
          { id: "bar-muscle-up", name: "Bar Muscle-Up", muscleGroup: "CALISTHENICS", category: "Pull Movements", equipment: "Bodyweight" },
          { id: "ring-muscle-up", name: "Ring Muscle-Up", muscleGroup: "CALISTHENICS", category: "Pull Movements", equipment: "Bodyweight" },
          { id: "australian-pullup", name: "Australian Pull-Up", muscleGroup: "CALISTHENICS", category: "Pull Movements", equipment: "Bodyweight" },
          { id: "inverted-row-calisthenics", name: "Inverted Row", muscleGroup: "CALISTHENICS", category: "Pull Movements", equipment: "Bodyweight" },
        ],
      },
      {
        id: "calisthenics-legs",
        name: "Leg Movements",
        muscleGroup: "CALISTHENICS",
        exercises: [
          { id: "squat-calisthenics", name: "Bodyweight Squat", muscleGroup: "CALISTHENICS", category: "Leg Movements", equipment: "Bodyweight" },
          { id: "jump-squat-calisthenics", name: "Jump Squat", muscleGroup: "CALISTHENICS", category: "Leg Movements", equipment: "Bodyweight" },
          { id: "pistol-squat-calisthenics", name: "Pistol Squat", muscleGroup: "CALISTHENICS", category: "Leg Movements", equipment: "Bodyweight" },
          { id: "shrimp-squat", name: "Shrimp Squat", muscleGroup: "CALISTHENICS", category: "Leg Movements", equipment: "Bodyweight" },
          { id: "bulgarian-split-squat-calisthenics", name: "Bulgarian Split Squat", muscleGroup: "CALISTHENICS", category: "Leg Movements", equipment: "Bodyweight" },
          { id: "lunge-calisthenics", name: "Lunge", muscleGroup: "CALISTHENICS", category: "Leg Movements", equipment: "Bodyweight" },
          { id: "walking-lunge-calisthenics", name: "Walking Lunge", muscleGroup: "CALISTHENICS", category: "Leg Movements", equipment: "Bodyweight" },
          { id: "jump-lunge", name: "Jump Lunge", muscleGroup: "CALISTHENICS", category: "Leg Movements", equipment: "Bodyweight" },
          { id: "calf-raise-calisthenics", name: "Calf Raise", muscleGroup: "CALISTHENICS", category: "Leg Movements", equipment: "Bodyweight" },
          { id: "single-leg-calf-raise-calisthenics", name: "Single-Leg Calf Raise", muscleGroup: "CALISTHENICS", category: "Leg Movements", equipment: "Bodyweight" },
          { id: "wall-sit-calisthenics", name: "Wall Sit", muscleGroup: "CALISTHENICS", category: "Leg Movements", equipment: "Bodyweight" },
          { id: "box-jump", name: "Box Jump", muscleGroup: "CALISTHENICS", category: "Leg Movements", equipment: "Bodyweight" },
          { id: "broad-jump", name: "Broad Jump", muscleGroup: "CALISTHENICS", category: "Leg Movements", equipment: "Bodyweight" },
        ],
      },
      {
        id: "calisthenics-core",
        name: "Core Movements",
        muscleGroup: "CALISTHENICS",
        exercises: [
          { id: "plank-calisthenics", name: "Plank", muscleGroup: "CALISTHENICS", category: "Core Movements", equipment: "Bodyweight" },
          { id: "side-plank-calisthenics", name: "Side Plank", muscleGroup: "CALISTHENICS", category: "Core Movements", equipment: "Bodyweight" },
          { id: "hollow-body-hold-calisthenics", name: "Hollow Body Hold", muscleGroup: "CALISTHENICS", category: "Core Movements", equipment: "Bodyweight" },
          { id: "arch-hold", name: "Arch Hold", muscleGroup: "CALISTHENICS", category: "Core Movements", equipment: "Bodyweight" },
          { id: "l-sit-calisthenics", name: "L-Sit", muscleGroup: "CALISTHENICS", category: "Core Movements", equipment: "Bodyweight" },
          { id: "v-sit", name: "V-Sit", muscleGroup: "CALISTHENICS", category: "Core Movements", equipment: "Bodyweight" },
          { id: "dragon-flag-calisthenics", name: "Dragon Flag", muscleGroup: "CALISTHENICS", category: "Core Movements", equipment: "Bodyweight" },
          { id: "hanging-leg-raise-calisthenics", name: "Hanging Leg Raise", muscleGroup: "CALISTHENICS", category: "Core Movements", equipment: "Bodyweight" },
          { id: "toes-to-bar-calisthenics", name: "Toes to Bar", muscleGroup: "CALISTHENICS", category: "Core Movements", equipment: "Bodyweight" },
          { id: "windshield-wipers-calisthenics", name: "Windshield Wipers", muscleGroup: "CALISTHENICS", category: "Core Movements", equipment: "Bodyweight" },
          { id: "ab-wheel-calisthenics", name: "Ab Wheel Rollout", muscleGroup: "CALISTHENICS", category: "Core Movements", equipment: "Bodyweight" },
          { id: "mountain-climbers-calisthenics", name: "Mountain Climbers", muscleGroup: "CALISTHENICS", category: "Core Movements", equipment: "Bodyweight" },
        ],
      },
      {
        id: "calisthenics-skills",
        name: "Skills & Holds",
        muscleGroup: "CALISTHENICS",
        exercises: [
          { id: "handstand-hold", name: "Handstand Hold", muscleGroup: "CALISTHENICS", category: "Skills & Holds", equipment: "Bodyweight" },
          { id: "wall-handstand", name: "Wall Handstand", muscleGroup: "CALISTHENICS", category: "Skills & Holds", equipment: "Bodyweight" },
          { id: "freestanding-handstand", name: "Freestanding Handstand", muscleGroup: "CALISTHENICS", category: "Skills & Holds", equipment: "Bodyweight" },
          { id: "handstand-walk", name: "Handstand Walk", muscleGroup: "CALISTHENICS", category: "Skills & Holds", equipment: "Bodyweight" },
          { id: "front-lever", name: "Front Lever", muscleGroup: "CALISTHENICS", category: "Skills & Holds", equipment: "Bodyweight" },
          { id: "front-lever-progression", name: "Front Lever Progression", muscleGroup: "CALISTHENICS", category: "Skills & Holds", equipment: "Bodyweight" },
          { id: "back-lever", name: "Back Lever", muscleGroup: "CALISTHENICS", category: "Skills & Holds", equipment: "Bodyweight" },
          { id: "back-lever-progression", name: "Back Lever Progression", muscleGroup: "CALISTHENICS", category: "Skills & Holds", equipment: "Bodyweight" },
          { id: "human-flag", name: "Human Flag", muscleGroup: "CALISTHENICS", category: "Skills & Holds", equipment: "Bodyweight" },
          { id: "planche", name: "Planche", muscleGroup: "CALISTHENICS", category: "Skills & Holds", equipment: "Bodyweight" },
          { id: "planche-lean", name: "Planche Lean", muscleGroup: "CALISTHENICS", category: "Skills & Holds", equipment: "Bodyweight" },
          { id: "tuck-planche", name: "Tuck Planche", muscleGroup: "CALISTHENICS", category: "Skills & Holds", equipment: "Bodyweight" },
          { id: "straddle-planche", name: "Straddle Planche", muscleGroup: "CALISTHENICS", category: "Skills & Holds", equipment: "Bodyweight" },
          { id: "full-planche", name: "Full Planche", muscleGroup: "CALISTHENICS", category: "Skills & Holds", equipment: "Bodyweight" },
          { id: "elbow-lever", name: "Elbow Lever", muscleGroup: "CALISTHENICS", category: "Skills & Holds", equipment: "Bodyweight" },
          { id: "crow-pose", name: "Crow Pose", muscleGroup: "CALISTHENICS", category: "Skills & Holds", equipment: "Bodyweight" },
        ],
      },
      {
        id: "calisthenics-dynamic",
        name: "Dynamic Movements",
        muscleGroup: "CALISTHENICS",
        exercises: [
          { id: "burpee-calisthenics", name: "Burpee", muscleGroup: "CALISTHENICS", category: "Dynamic Movements", equipment: "Bodyweight" },
          { id: "burpee-pullup", name: "Burpee Pull-Up", muscleGroup: "CALISTHENICS", category: "Dynamic Movements", equipment: "Bodyweight" },
          { id: "clapping-pushup", name: "Clapping Push-Up", muscleGroup: "CALISTHENICS", category: "Dynamic Movements", equipment: "Bodyweight" },
          { id: "explosive-pullup", name: "Explosive Pull-Up", muscleGroup: "CALISTHENICS", category: "Dynamic Movements", equipment: "Bodyweight" },
          { id: "bar-hop", name: "Bar Hop", muscleGroup: "CALISTHENICS", category: "Dynamic Movements", equipment: "Bodyweight" },
          { id: "kipping-pullup", name: "Kipping Pull-Up", muscleGroup: "CALISTHENICS", category: "Dynamic Movements", equipment: "Bodyweight" },
          { id: "360-pullup", name: "360 Pull-Up", muscleGroup: "CALISTHENICS", category: "Dynamic Movements", equipment: "Bodyweight" },
          { id: "clapping-muscle-up", name: "Clapping Muscle-Up", muscleGroup: "CALISTHENICS", category: "Dynamic Movements", equipment: "Bodyweight" },
          { id: "swing-to-handstand", name: "Swing to Handstand", muscleGroup: "CALISTHENICS", category: "Dynamic Movements", equipment: "Bodyweight" },
        ],
      },
    ],
  },
  {
    id: "yoga",
    name: "YOGA",
    categories: [
      {
        id: "yoga-standing",
        name: "Standing Poses",
        muscleGroup: "YOGA",
        exercises: [
          { id: "mountain-pose", name: "Mountain Pose (Tadasana)", muscleGroup: "YOGA", category: "Standing Poses", equipment: "Bodyweight" },
          { id: "warrior-1", name: "Warrior I (Virabhadrasana I)", muscleGroup: "YOGA", category: "Standing Poses", equipment: "Bodyweight" },
          { id: "warrior-2", name: "Warrior II (Virabhadrasana II)", muscleGroup: "YOGA", category: "Standing Poses", equipment: "Bodyweight" },
          { id: "warrior-3", name: "Warrior III (Virabhadrasana III)", muscleGroup: "YOGA", category: "Standing Poses", equipment: "Bodyweight" },
          { id: "reverse-warrior", name: "Reverse Warrior", muscleGroup: "YOGA", category: "Standing Poses", equipment: "Bodyweight" },
          { id: "triangle-pose", name: "Triangle Pose (Trikonasana)", muscleGroup: "YOGA", category: "Standing Poses", equipment: "Bodyweight" },
          { id: "extended-side-angle", name: "Extended Side Angle (Utthita Parsvakonasana)", muscleGroup: "YOGA", category: "Standing Poses", equipment: "Bodyweight" },
          { id: "half-moon-pose", name: "Half Moon Pose (Ardha Chandrasana)", muscleGroup: "YOGA", category: "Standing Poses", equipment: "Bodyweight" },
          { id: "standing-forward-bend", name: "Standing Forward Bend (Uttanasana)", muscleGroup: "YOGA", category: "Standing Poses", equipment: "Bodyweight" },
          { id: "wide-legged-forward-fold", name: "Wide-Legged Forward Fold (Prasarita Padottanasana)", muscleGroup: "YOGA", category: "Standing Poses", equipment: "Bodyweight" },
          { id: "pyramid-pose", name: "Pyramid Pose (Parsvottanasana)", muscleGroup: "YOGA", category: "Standing Poses", equipment: "Bodyweight" },
          { id: "chair-pose", name: "Chair Pose (Utkatasana)", muscleGroup: "YOGA", category: "Standing Poses", equipment: "Bodyweight" },
          { id: "high-lunge", name: "High Lunge", muscleGroup: "YOGA", category: "Standing Poses", equipment: "Bodyweight" },
          { id: "crescent-lunge", name: "Crescent Lunge", muscleGroup: "YOGA", category: "Standing Poses", equipment: "Bodyweight" },
        ],
      },
      {
        id: "yoga-balance",
        name: "Balance Poses",
        muscleGroup: "YOGA",
        exercises: [
          { id: "tree-pose", name: "Tree Pose (Vrksasana)", muscleGroup: "YOGA", category: "Balance Poses", equipment: "Bodyweight" },
          { id: "eagle-pose", name: "Eagle Pose (Garudasana)", muscleGroup: "YOGA", category: "Balance Poses", equipment: "Bodyweight" },
          { id: "dancer-pose", name: "Dancer Pose (Natarajasana)", muscleGroup: "YOGA", category: "Balance Poses", equipment: "Bodyweight" },
          { id: "standing-split", name: "Standing Split (Urdhva Prasarita Eka Padasana)", muscleGroup: "YOGA", category: "Balance Poses", equipment: "Bodyweight" },
          { id: "extended-hand-to-big-toe", name: "Extended Hand to Big Toe (Utthita Hasta Padangusthasana)", muscleGroup: "YOGA", category: "Balance Poses", equipment: "Bodyweight" },
          { id: "airplane-pose", name: "Airplane Pose", muscleGroup: "YOGA", category: "Balance Poses", equipment: "Bodyweight" },
          { id: "half-moon-yoga", name: "Half Moon Pose", muscleGroup: "YOGA", category: "Balance Poses", equipment: "Bodyweight" },
        ],
      },
      {
        id: "yoga-seated",
        name: "Seated Poses",
        muscleGroup: "YOGA",
        exercises: [
          { id: "easy-pose", name: "Easy Pose (Sukhasana)", muscleGroup: "YOGA", category: "Seated Poses", equipment: "Bodyweight" },
          { id: "lotus-pose", name: "Lotus Pose (Padmasana)", muscleGroup: "YOGA", category: "Seated Poses", equipment: "Bodyweight" },
          { id: "half-lotus", name: "Half Lotus (Ardha Padmasana)", muscleGroup: "YOGA", category: "Seated Poses", equipment: "Bodyweight" },
          { id: "bound-angle-pose", name: "Bound Angle Pose (Baddha Konasana)", muscleGroup: "YOGA", category: "Seated Poses", equipment: "Bodyweight" },
          { id: "seated-forward-bend-yoga", name: "Seated Forward Bend (Paschimottanasana)", muscleGroup: "YOGA", category: "Seated Poses", equipment: "Bodyweight" },
          { id: "head-to-knee-forward-bend", name: "Head-to-Knee Forward Bend (Janu Sirsasana)", muscleGroup: "YOGA", category: "Seated Poses", equipment: "Bodyweight" },
          { id: "seated-wide-angle", name: "Seated Wide Angle (Upavistha Konasana)", muscleGroup: "YOGA", category: "Seated Poses", equipment: "Bodyweight" },
          { id: "boat-pose", name: "Boat Pose (Navasana)", muscleGroup: "YOGA", category: "Seated Poses", equipment: "Bodyweight" },
          { id: "half-boat-pose", name: "Half Boat Pose (Ardha Navasana)", muscleGroup: "YOGA", category: "Seated Poses", equipment: "Bodyweight" },
          { id: "cow-face-pose", name: "Cow Face Pose (Gomukhasana)", muscleGroup: "YOGA", category: "Seated Poses", equipment: "Bodyweight" },
          { id: "seated-twist", name: "Seated Twist (Ardha Matsyendrasana)", muscleGroup: "YOGA", category: "Seated Poses", equipment: "Bodyweight" },
          { id: "sage-twist", name: "Sage Twist (Marichyasana)", muscleGroup: "YOGA", category: "Seated Poses", equipment: "Bodyweight" },
        ],
      },
      {
        id: "yoga-backbends",
        name: "Backbends",
        muscleGroup: "YOGA",
        exercises: [
          { id: "cobra-pose-yoga", name: "Cobra Pose (Bhujangasana)", muscleGroup: "YOGA", category: "Backbends", equipment: "Bodyweight" },
          { id: "upward-facing-dog", name: "Upward Facing Dog (Urdhva Mukha Svanasana)", muscleGroup: "YOGA", category: "Backbends", equipment: "Bodyweight" },
          { id: "locust-pose", name: "Locust Pose (Salabhasana)", muscleGroup: "YOGA", category: "Backbends", equipment: "Bodyweight" },
          { id: "bow-pose", name: "Bow Pose (Dhanurasana)", muscleGroup: "YOGA", category: "Backbends", equipment: "Bodyweight" },
          { id: "bridge-pose-yoga", name: "Bridge Pose (Setu Bandhasana)", muscleGroup: "YOGA", category: "Backbends", equipment: "Bodyweight" },
          { id: "wheel-pose", name: "Wheel Pose (Urdhva Dhanurasana)", muscleGroup: "YOGA", category: "Backbends", equipment: "Bodyweight" },
          { id: "camel-pose", name: "Camel Pose (Ustrasana)", muscleGroup: "YOGA", category: "Backbends", equipment: "Bodyweight" },
          { id: "sphinx-pose", name: "Sphinx Pose", muscleGroup: "YOGA", category: "Backbends", equipment: "Bodyweight" },
          { id: "fish-pose", name: "Fish Pose (Matsyasana)", muscleGroup: "YOGA", category: "Backbends", equipment: "Bodyweight" },
          { id: "king-pigeon", name: "King Pigeon Pose (Eka Pada Rajakapotasana)", muscleGroup: "YOGA", category: "Backbends", equipment: "Bodyweight" },
        ],
      },
      {
        id: "yoga-hip-openers",
        name: "Hip Openers",
        muscleGroup: "YOGA",
        exercises: [
          { id: "pigeon-pose-yoga", name: "Pigeon Pose (Eka Pada Rajakapotasana)", muscleGroup: "YOGA", category: "Hip Openers", equipment: "Bodyweight" },
          { id: "double-pigeon", name: "Double Pigeon (Agnistambhasana)", muscleGroup: "YOGA", category: "Hip Openers", equipment: "Bodyweight" },
          { id: "lizard-pose-yoga", name: "Lizard Pose (Utthan Pristhasana)", muscleGroup: "YOGA", category: "Hip Openers", equipment: "Bodyweight" },
          { id: "frog-pose-yoga", name: "Frog Pose (Mandukasana)", muscleGroup: "YOGA", category: "Hip Openers", equipment: "Bodyweight" },
          { id: "garland-pose", name: "Garland Pose (Malasana)", muscleGroup: "YOGA", category: "Hip Openers", equipment: "Bodyweight" },
          { id: "happy-baby-yoga", name: "Happy Baby (Ananda Balasana)", muscleGroup: "YOGA", category: "Hip Openers", equipment: "Bodyweight" },
          { id: "fire-log-yoga", name: "Fire Log Pose (Agnistambhasana)", muscleGroup: "YOGA", category: "Hip Openers", equipment: "Bodyweight" },
          { id: "low-lunge", name: "Low Lunge (Anjaneyasana)", muscleGroup: "YOGA", category: "Hip Openers", equipment: "Bodyweight" },
          { id: "half-splits", name: "Half Splits (Ardha Hanumanasana)", muscleGroup: "YOGA", category: "Hip Openers", equipment: "Bodyweight" },
          { id: "monkey-pose", name: "Monkey Pose / Splits (Hanumanasana)", muscleGroup: "YOGA", category: "Hip Openers", equipment: "Bodyweight" },
        ],
      },
      {
        id: "yoga-inversions",
        name: "Inversions",
        muscleGroup: "YOGA",
        exercises: [
          { id: "downward-dog-yoga", name: "Downward Facing Dog (Adho Mukha Svanasana)", muscleGroup: "YOGA", category: "Inversions", equipment: "Bodyweight" },
          { id: "dolphin-pose", name: "Dolphin Pose", muscleGroup: "YOGA", category: "Inversions", equipment: "Bodyweight" },
          { id: "headstand", name: "Headstand (Sirsasana)", muscleGroup: "YOGA", category: "Inversions", equipment: "Bodyweight" },
          { id: "tripod-headstand", name: "Tripod Headstand", muscleGroup: "YOGA", category: "Inversions", equipment: "Bodyweight" },
          { id: "forearm-stand", name: "Forearm Stand (Pincha Mayurasana)", muscleGroup: "YOGA", category: "Inversions", equipment: "Bodyweight" },
          { id: "handstand-yoga", name: "Handstand (Adho Mukha Vrksasana)", muscleGroup: "YOGA", category: "Inversions", equipment: "Bodyweight" },
          { id: "shoulder-stand", name: "Shoulder Stand (Salamba Sarvangasana)", muscleGroup: "YOGA", category: "Inversions", equipment: "Bodyweight" },
          { id: "plow-pose", name: "Plow Pose (Halasana)", muscleGroup: "YOGA", category: "Inversions", equipment: "Bodyweight" },
          { id: "legs-up-wall", name: "Legs Up the Wall (Viparita Karani)", muscleGroup: "YOGA", category: "Inversions", equipment: "Bodyweight" },
        ],
      },
      {
        id: "yoga-arm-balances",
        name: "Arm Balances",
        muscleGroup: "YOGA",
        exercises: [
          { id: "crow-pose-yoga", name: "Crow Pose (Kakasana)", muscleGroup: "YOGA", category: "Arm Balances", equipment: "Bodyweight" },
          { id: "crane-pose", name: "Crane Pose (Bakasana)", muscleGroup: "YOGA", category: "Arm Balances", equipment: "Bodyweight" },
          { id: "side-crow", name: "Side Crow (Parsva Bakasana)", muscleGroup: "YOGA", category: "Arm Balances", equipment: "Bodyweight" },
          { id: "firefly-pose", name: "Firefly Pose (Tittibhasana)", muscleGroup: "YOGA", category: "Arm Balances", equipment: "Bodyweight" },
          { id: "flying-pigeon", name: "Flying Pigeon (Eka Pada Galavasana)", muscleGroup: "YOGA", category: "Arm Balances", equipment: "Bodyweight" },
          { id: "eight-angle-pose", name: "Eight-Angle Pose (Astavakrasana)", muscleGroup: "YOGA", category: "Arm Balances", equipment: "Bodyweight" },
          { id: "peacock-pose", name: "Peacock Pose (Mayurasana)", muscleGroup: "YOGA", category: "Arm Balances", equipment: "Bodyweight" },
          { id: "scale-pose", name: "Scale Pose (Tolasana)", muscleGroup: "YOGA", category: "Arm Balances", equipment: "Bodyweight" },
          { id: "hummingbird-pose", name: "Hummingbird Pose (Maksikanagasana)", muscleGroup: "YOGA", category: "Arm Balances", equipment: "Bodyweight" },
        ],
      },
      {
        id: "yoga-twists",
        name: "Twists",
        muscleGroup: "YOGA",
        exercises: [
          { id: "supine-spinal-twist", name: "Supine Spinal Twist (Supta Matsyendrasana)", muscleGroup: "YOGA", category: "Twists", equipment: "Bodyweight" },
          { id: "revolved-triangle", name: "Revolved Triangle (Parivrtta Trikonasana)", muscleGroup: "YOGA", category: "Twists", equipment: "Bodyweight" },
          { id: "revolved-side-angle", name: "Revolved Side Angle (Parivrtta Parsvakonasana)", muscleGroup: "YOGA", category: "Twists", equipment: "Bodyweight" },
          { id: "revolved-chair", name: "Revolved Chair (Parivrtta Utkatasana)", muscleGroup: "YOGA", category: "Twists", equipment: "Bodyweight" },
          { id: "revolved-crescent-lunge", name: "Revolved Crescent Lunge", muscleGroup: "YOGA", category: "Twists", equipment: "Bodyweight" },
          { id: "bharadvaja-twist", name: "Bharadvaja's Twist (Bharadvajasana)", muscleGroup: "YOGA", category: "Twists", equipment: "Bodyweight" },
          { id: "noose-pose", name: "Noose Pose (Pasasana)", muscleGroup: "YOGA", category: "Twists", equipment: "Bodyweight" },
        ],
      },
      {
        id: "yoga-restorative",
        name: "Restorative Poses",
        muscleGroup: "YOGA",
        exercises: [
          { id: "childs-pose-yoga", name: "Child's Pose (Balasana)", muscleGroup: "YOGA", category: "Restorative Poses", equipment: "Bodyweight" },
          { id: "extended-childs-pose", name: "Extended Child's Pose", muscleGroup: "YOGA", category: "Restorative Poses", equipment: "Bodyweight" },
          { id: "corpse-pose", name: "Corpse Pose (Savasana)", muscleGroup: "YOGA", category: "Restorative Poses", equipment: "Bodyweight" },
          { id: "reclining-bound-angle", name: "Reclining Bound Angle (Supta Baddha Konasana)", muscleGroup: "YOGA", category: "Restorative Poses", equipment: "Bodyweight" },
          { id: "reclining-hero-pose", name: "Reclining Hero Pose (Supta Virasana)", muscleGroup: "YOGA", category: "Restorative Poses", equipment: "Bodyweight" },
          { id: "supported-fish-pose", name: "Supported Fish Pose", muscleGroup: "YOGA", category: "Restorative Poses", equipment: "Bodyweight" },
          { id: "legs-up-wall-yoga", name: "Legs Up the Wall", muscleGroup: "YOGA", category: "Restorative Poses", equipment: "Bodyweight" },
          { id: "wide-knee-childs-pose", name: "Wide-Knee Child's Pose", muscleGroup: "YOGA", category: "Restorative Poses", equipment: "Bodyweight" },
        ],
      },
      {
        id: "yoga-flows",
        name: "Flows & Sequences",
        muscleGroup: "YOGA",
        exercises: [
          { id: "sun-salutation-a", name: "Sun Salutation A (Surya Namaskar A)", muscleGroup: "YOGA", category: "Flows & Sequences", equipment: "Bodyweight" },
          { id: "sun-salutation-b", name: "Sun Salutation B (Surya Namaskar B)", muscleGroup: "YOGA", category: "Flows & Sequences", equipment: "Bodyweight" },
          { id: "moon-salutation", name: "Moon Salutation (Chandra Namaskar)", muscleGroup: "YOGA", category: "Flows & Sequences", equipment: "Bodyweight" },
          { id: "cat-cow-flow", name: "Cat-Cow Flow", muscleGroup: "YOGA", category: "Flows & Sequences", equipment: "Bodyweight" },
          { id: "vinyasa-flow", name: "Vinyasa Flow", muscleGroup: "YOGA", category: "Flows & Sequences", equipment: "Bodyweight" },
          { id: "warrior-flow", name: "Warrior Flow Sequence", muscleGroup: "YOGA", category: "Flows & Sequences", equipment: "Bodyweight" },
          { id: "hip-opening-flow", name: "Hip Opening Flow", muscleGroup: "YOGA", category: "Flows & Sequences", equipment: "Bodyweight" },
          { id: "morning-yoga-flow", name: "Morning Yoga Flow", muscleGroup: "YOGA", category: "Flows & Sequences", equipment: "Bodyweight" },
          { id: "evening-yoga-flow", name: "Evening Yoga Flow", muscleGroup: "YOGA", category: "Flows & Sequences", equipment: "Bodyweight" },
        ],
      },
    ],
  },
];

export default exerciseLibrary;
