import { MealRecommendation } from "@/types/diet";

export const MEAL_RECOMMENDATIONS: MealRecommendation[] = [
  {
    id: "1",
    name: "Idli Sambar with Coconut Chutney",
    cuisine: "south-indian",
    calories: 320,
    macros: { protein: 12, carbs: 58, fat: 6 },
    prepTime: 25,
    ingredients: [
      "4 idlis",
      "1 cup sambar",
      "2 tbsp coconut chutney",
      "curry leaves",
    ],
    tags: ["Fermented", "High Protein", "Light"],
  },
  {
    id: "2",
    name: "Moong Dal Cheela with Mint Chutney",
    cuisine: "north-indian",
    calories: 280,
    macros: { protein: 18, carbs: 35, fat: 8 },
    prepTime: 15,
    ingredients: [
      "1 cup moong dal",
      "onions",
      "tomatoes",
      "green chilies",
      "mint leaves",
    ],
    tags: ["High Protein", "Quick", "Vegetarian"],
  },
  {
    id: "3",
    name: "Paneer Tikka Bowl",
    cuisine: "north-indian",
    calories: 420,
    macros: { protein: 32, carbs: 28, fat: 22 },
    prepTime: 30,
    ingredients: [
      "200g paneer",
      "yogurt",
      "tikka masala",
      "bell peppers",
      "onions",
      "brown rice",
    ],
    tags: ["High Protein", "Grilled"],
  },
  {
    id: "4",
    name: "Dosa with Peanut Chutney",
    cuisine: "south-indian",
    calories: 310,
    macros: { protein: 10, carbs: 52, fat: 8 },
    prepTime: 20,
    ingredients: ["dosa batter", "peanuts", "coconut", "tamarind", "jaggery"],
    tags: ["Fermented", "Crispy"],
  },
  {
    id: "5",
    name: "Chickpea Salad Bowl",
    cuisine: "vegan",
    calories: 350,
    macros: { protein: 16, carbs: 48, fat: 12 },
    prepTime: 10,
    ingredients: [
      "chickpeas",
      "cucumber",
      "tomatoes",
      "lemon",
      "olive oil",
      "chat masala",
    ],
    tags: ["Quick", "Fresh", "Protein-Rich"],
  },
  {
    id: "6",
    name: "Poha with Peanuts",
    cuisine: "quick",
    calories: 260,
    macros: { protein: 8, carbs: 42, fat: 8 },
    prepTime: 12,
    ingredients: ["poha", "peanuts", "curry leaves", "turmeric", "mustard"],
    tags: ["Quick", "Light", "Traditional"],
  },
  {
    id: "7",
    name: "Masala Oats",
    cuisine: "quick",
    calories: 240,
    macros: { protein: 10, carbs: 38, fat: 6 },
    prepTime: 8,
    ingredients: ["oats", "vegetables", "garam masala", "tomatoes"],
    tags: ["Quick", "Fiber-Rich", "Healthy"],
  },
  {
    id: "8",
    name: "Khichdi with Ghee",
    cuisine: "ayurvedic",
    calories: 330,
    macros: { protein: 14, carbs: 54, fat: 8 },
    prepTime: 25,
    ingredients: ["rice", "moong dal", "ghee", "cumin", "turmeric", "ginger"],
    tags: ["Healing", "Comfort", "Easy Digest"],
  },
  {
    id: "9",
    name: "Quinoa Upma",
    cuisine: "vegan",
    calories: 290,
    macros: { protein: 12, carbs: 44, fat: 8 },
    prepTime: 15,
    ingredients: [
      "quinoa",
      "mustard seeds",
      "curry leaves",
      "vegetables",
      "lemon",
    ],
    tags: ["Protein-Rich", "Gluten-Free"],
  },
  {
    id: "10",
    name: "Dal Tadka with Roti",
    cuisine: "north-indian",
    calories: 380,
    macros: { protein: 16, carbs: 58, fat: 10 },
    prepTime: 30,
    ingredients: [
      "toor dal",
      "tomatoes",
      "garlic",
      "cumin",
      "ghee",
      "whole wheat roti",
    ],
    tags: ["Protein-Rich", "Comfort"],
  },
];
